In [1]:
from snowflake.snowpark.session import Session
import snowflake.snowpark.functions as F
import snowflake.snowpark.types as T
from snowflake.snowpark.window import Window
from sklearn import preprocessing # https://github.com/Snowflake-Labs/snowpark-python-demos/tree/main/sp4py_utilities
from snowflake.snowpark.functions import col

import getpass
import pandas as pd
import matplotlib.pyplot as plt

In [91]:
#nj07294.ap-southeast-1

In [2]:
accountname = 'nj07294.ap-southeast-1'
#accountname = getpass.getpass() # ORGNAME-ACCOUNTNAME (separated by minus sign)

In [3]:
username = getpass.getpass()    # SNOWFLAKE-USERNAME

In [4]:
password = getpass.getpass()    # SNOWFLAKE-PASSWORD

In [5]:
connection_parameters = {
    "account": accountname,
    "user": username,
    "password": password,
    "role": "ACCOUNTADMIN",
    "database": "FROSTBYTE_TASTY_BYTES",

    "warehouse": "HOL_WH"
}

session = Session.builder.configs(connection_parameters).create()

# Filter

In [11]:
sdf = session.table('ANALYTICS.ORDERS_V')
df=sdf.filter(col("COUNTRY")=='United States')

In [97]:
df=sdf.filter(col("COUNTRY")=='United States')

In [98]:
df.show()

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"DATE"      |"ORDER_ID"  |"TRUCK_ID"  |"ORDER_TS"           |"ORDER_DETAIL_ID"  |"LINE_NUMBER"  |"TRUCK_BRAND_NAME"  |"MENU_TYPE"  |"PRIMARY_CITY"  |"REGION"  |"COUNTRY"      |"FRANCHISE_FLAG"  |"FRANCHISE_ID"  |"FRANCHISEE_FIRST_NAME"  |"FRANCHISEE_LAST_NAME"  |"LOCATION_ID"  |"CUSTOMER_ID"  |"FIRST_NAME"  |"LAST_NAME"  |"E_MAIL"  |"PHONE_NUMBER"  |"CHILDREN_COUNT"  |"GENDER"  |"MARITAL_STATUS"  |"MENU_ITEM_ID"  |"MENU_ITEM_NAME"       |"QUANTITY"  |"UNIT_PRICE"  |"PRICE"  |"ORDER_AMOUNT"  |"ORDER_TAX_AMOUNT"  |"ORDER_DISCOUNT_AMOUNT"  |"ORDER_TOTAL"  |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2021-09-10  |440500498   |68          |2021-09-10 11:48:05  |852793964          |1              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |82              |Chicken Pot Pie Crepe  |1           |15.0000       |15.0000  |47.0000         |NULL                |NULL                     |47.0000        |
|2021-09-10  |440500498   |68          |2021-09-10 11:48:05  |852793963          |0              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |81              |Breakfast Crepe        |1           |12.0000       |12.0000  |47.0000         |NULL                |NULL                     |47.0000        |
|2021-09-10  |440500498   |68          |2021-09-10 11:48:05  |852793965          |2              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |83              |Crepe Suzette          |2           |9.0000        |18.0000  |47.0000         |NULL                |NULL                     |47.0000        |
|2021-09-10  |440500498   |68          |2021-09-10 11:48:05  |852793966          |3              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |84              |Bottled Water          |1           |2.0000        |2.0000   |47.0000         |NULL                |NULL                     |47.0000        |
|2021-09-10  |440500570   |68          |2021-09-10 12:16:57  |852794156          |0              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |83              |Crepe Suzette          |1           |9.0000        |9.0000   |9.0000          |NULL                |NULL                     |9.0000         |
|2021-09-10  |440500853   |68          |2021-09-10 15:38:00  |852794883          |1              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3124           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |85              |Bottled Soda           |1           |3.0000        |3.0000   |21.0000         |NULL                |NULL                     |21.0000        |
|2021-09-10  |440500853   |68          |2021-09-10 15:38:00  |852794882          |0              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3124           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |83              |Crepe Suzette          |2           |9.0000        |18.0000  |21.0000         |NULL                |NULL                     |21.0000        |
|2021-09-10  |440500879   |68          |2021-09-10 15:56:00  |852794941          |0              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3124           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |83              |Crepe Suzette          |3           |9.0000        |27.0000  |30.0000         |NULL                |NULL                     |30.0000        |
|2021-09-10  |440500879   |68          |2021-09-10 15:56:00  |852794942          |1              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3124           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |85              |Bottled Soda           |1           |3.0000        |3.0000   |30.0000         |NULL                |NULL                     |30.0000        |
|2021-09-10  |440500935   |68          |2021-09-10 16:25:46  |852795076          |2              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3124           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |83              |Crepe Suzette          |1           |9.0000        |9.0000   |48.0000         |NULL                |NULL                     |48.0000        |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### Extracting weather data

In [99]:
connection_parameters = {
    "account": accountname,
    "user": username,
    "password": password,
    "role": "ACCOUNTADMIN",
    "database": "GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI",

    "warehouse": "HOL_WH"
}

wea_session = Session.builder.configs(connection_parameters).create()
wdf = wea_session.table('STANDARD_TILE.HISTORY_DAY')

In [100]:
wdf.show()

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"POSTAL_CODE"  |"COUNTRY"  |"DATE_VALID_STD"  |"DOY_STD"  |"MIN_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_AIR_2M_F"  |"MAX_TEMPERATURE_AIR_2M_F"  |"MIN_TEMPERATURE_WETBULB_2M_F"  |"AVG_TEMPERATURE_WETBULB_2M_F"  |"MAX_TEMPERATURE_WETBULB_2M_F"  |"MIN_TEMPERATURE_DEWPOINT_2M_F"  |"AVG_TEMPERATURE_DEWPOINT_2M_F"  |"MAX_TEMPERATURE_DEWPOINT_2M_F"  |"MIN_TEMPERATURE_FEELSLIKE_2M_F"  |"AVG_TEMPERATURE_FEELSLIKE_2M_F"  |"MAX_TEMPERATURE_FEELSLIKE_2M_F"  |"MIN_TEMPERATURE_WINDCHILL_2M_F"  |"AVG_TEMPERATURE_WINDCHILL_2M_F"  |"MAX_TEMPERATURE_WINDCHILL_2M_F"  |"MIN_TEMPERATURE_HEATINDEX_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"MAX_TEMPERATURE_HEATINDEX_2M_F"  |"MIN_HUMIDITY_RELATIVE_2M_PCT"  |"AVG_HUMIDITY_RELATIVE_2M_PCT"  |"MAX_HUMIDITY_RELATIVE_2M_PCT"  |"MIN_HUMIDITY_SPECIFIC_2M_GPKG"  |"AVG_HUMIDITY_SPECIFIC_2M_GPKG"  |"MAX_HUMIDITY_SPECIFIC_2M_GPKG"  |"MIN_PRESSURE_2M_MB"  |"AVG_PRESSURE_2M_MB"  |"MAX_PRESSURE_2M_MB"  |"MIN_PRESSURE_TENDENCY_2M_MB"  |"AVG_PRESSURE_TENDENCY_2M_MB"  |"MAX_PRESSURE_TENDENCY_2M_MB"  |"MIN_PRESSURE_MEAN_SEA_LEVEL_MB"  |"AVG_PRESSURE_MEAN_SEA_LEVEL_MB"  |"MAX_PRESSURE_MEAN_SEA_LEVEL_MB"  |"MIN_WIND_SPEED_10M_MPH"  |"AVG_WIND_SPEED_10M_MPH"  |"MAX_WIND_SPEED_10M_MPH"  |"AVG_WIND_DIRECTION_10M_DEG"  |"MIN_WIND_SPEED_80M_MPH"  |"AVG_WIND_SPEED_80M_MPH"  |"MAX_WIND_SPEED_80M_MPH"  |"AVG_WIND_DIRECTION_80M_DEG"  |"MIN_WIND_SPEED_100M_MPH"  |"AVG_WIND_SPEED_100M_MPH"  |"MAX_WIND_SPEED_100M_MPH"  |"AVG_WIND_DIRECTION_100M_DEG"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"MIN_CLOUD_COVER_TOT_PCT"  |"AVG_CLOUD_COVER_TOT_PCT"  |"MAX_CLOUD_COVER_TOT_PCT"  |"MIN_RADIATION_SOLAR_TOTAL_WPM2"  |"AVG_RADIATION_SOLAR_TOTAL_WPM2"  |"MAX_RADIATION_SOLAR_TOTAL_WPM2"  |"TOT_RADIATION_SOLAR_TOTAL_WPM2"  |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|71678          |US         |2021-06-24        |175        |72.0                        |82.7                        |92.8                        |70.0                            |75.4                            |78.4                            |69.0                             |72.4                             |75.1                             |72.0                              |88.5                              |102.1                             |72.0                              |82.7                              |92.8                              |72.0                              |88.5                              |102.1                             |51                              |73                              |91                              |15.1                             |17.1                             |18.7                             |1007.84               |1009.54               |1011.22               |-0.9                           |-0.1                           |0.5                            |1013.00                           |1015.40                           |1017.80                           |0.4                       |6.2                       |8.9                       |175                           |7.5                       |11.5                      |18.4                      |170                           |7.6                        |11.9                       |19.1                       |171                            |0.00                    |0.00               |0.0                 |0                          |22                         |85                         |0.0                               |288.4                             |911.3                             |6922.5                            |
|71701          |US         |2021-06-24        |175        |72.9                        |83.7                        |95.3                        |71.0                            |76.5                            |79.7                            |70.2                             |73.7                             |76.7                             |72.9                              |90.4                              |106.1                             |72.9                              |83.7                              |95.3                              |72.9                              |90.4                              |106.1                             |49                              |74                              |96                              |15.7                             |17.9                             |19.7                             |1007.95               |1009.82               |1011.70               |-1.0                           |-0.1                           |0.7                            |1012.40                           |1014.90                           |1017.10                           |0.1                       |4.9                       |9.2                       |173                           |7.2                       |10.8                      |16.2                      |170                           |8.1                        |11.0                       |16.9                       |171                            |0.00                    |0.00               |0.0                 |0                          |32                         |100                        |0.0                               |237.0                             |865.5                             |5686.7                            |
|71858          |US         |2021-06-24        |175        |73.4                        |83.8                        |93.6                        |72.1                            |76.2                            |78.6                            |71.2                             |73.2                             |75.4                             |73.4                              |90.1                              |102.4                             |73.4                              |83.8                              |93.6                              |73.4                              |90.1                              |102.4                             |48                              |73                              |97                              |16.5                             |17.7                             |18.9                             |1000.26               |1002.00               |1003.78               |-1.0                           |-0.1                           |0.7                            |1012.20                           |1014.60                           |1016.70                           |1.6                       |5.2                       |8.2                       |180                           |7.9                       |10.9                      |16.5                      |173                           |7.1                        |11.0                       |16.4                       |177                            |0.00                    |0.00               |0.0                 |0                          |23                         |97                         |0.0                               |274.1                             |874.3                             |6579.9                            |
|72085          |US         |2021-06-24        |175        |67.6                        |81.0                        |91.4                        |66.0                            |74.4                            |79.2                            |63.8                             |71.8                             |75.3                             |67.6                              |86.8                              |101.8                             |67.6                              |81.0                              |91.4                              |67.6                              |86.8                              |101.8                             |57                              |75                              |93                              |12.7                             |17.0                             |19.0                             |1001.27               |1003.43               |1005.21               |-0.7                           |-0.1                           |1.0                            |1012.30                           |1014.80                           |1016.70                           |0.3                       |5.7                       |10.0                      |176                           |8.1                       |11.4                      |16.5                      |181                           |7.7                        |10.6                       |13.3                       |184                            |0.00                    |0.00               |0.0                 |0                          |33                         |100                        |0.0                               |265.8                             |779.8                             |6379.2                            |
|72124          |US         |2021-06-24        |175        |71.8                        |82.7                        |92.3                        |69.2                            |75.3                            |79.2                            |67.9                             |72.5                             |74.7                             |71.8                              |88.7                              |103.1                             |71.8                              |82.7                              |92.3                              |71.8                              |88.7                              |103.1                             |54                              |73                              |91                              |14.6                             |17.3                             |18.7                             |1000.18               |1002.04               |1003.60               |-1.0                           |-0.1                           |0.5                            |1012.30                           |1014.80                           |1016.90                           |1.9                       |5.7                       |8.9                       |184                           |8.1                       |11.3                      |16.4                      |176                           |8.6                        |11.1                       |16.2                       |180                            |0.00                    |0.00               |0.0                 |0                          |37                         |100                        |0.0                               |252.4                             |873.3                             |6056.3                            |
|72125          |US         |2021-06-24        |175        |72.1                        |82.7                        |91.8                        |68.2                            |76.1                            |80.4                            |66.4                             |73.7                             |77.2                             |72.1                              |89.8                              |103.9                             |72.1                              |82.7                              |91.8                              |72.1                              |89.8                              |103.9                             |59                              |75                              |89                              |14.0                             |18.2                             |20.4                             |993.60                |995.69                |997.28                |-1.0                           |-0.1                           |0.7                            |1012.00                           |1014.30                           |1016.20                           |0.6                       |4.6                       |8.6                       |185                           |8.2                       |11.0                      |15.4                      |178                           |6.3                        |9.7                        |13.0                       |180                            |0.00                    |0.00               |0.0                 |0                          |26                         |99                         |0.0                               |267.0                             |788.8                             |6407.7                            |
|72130          |US         |2021-06-24        |175        |68.3                        |77.8                        |87.0                        |64.4                            |72.0                            |76.7                            |62.3                             |69.6                             |72.7                             |68.3                              |81.2                              |94.2                              |68.3                              |77.8                              |87.0                              |68.3                              |81.2                              |94.2                              |61                              |77                              |94                              |12.3                             |16.1                             |18.0                             |974.10                |975.93                |977.40                |-0.8                           |-0.1                           |0.7                            |1011.80                           |1014.30                           |1016.10                           |4.3                       |8.1                       |11.4                      |185                           |7.8                       |12.9                      |17.1                      |187                           |8.8                        |15.1                       |19.7                       |188                            |0.00                    |0.00               |0.0                 |0                          |44                         |100                        |0.0                               |235.1                             |763.8                             |5642.0                            |
|72183          |US         |2021-06-24        |175        |72.1                        |82.5                        |92.1                        |69.9                            |75.4                            |79.5                            |68.8                             |72.6                             |74.9                             |72.1                              |88.5                              |102.9                             |72.1                              |82.5                              |92.1                              |72.1                              |88.5                              |102.9                             |55                              |73                              |91                              |15.0                             |17.3                             |18.9                             |1004.58               |1006.38               |1007.93               |-1.1                           |-0.1                           |0.6                            |1012.40                           |1014.90                           |1017.10                           |1.6                       |5.8                       |8.7                       |185                           |7.9                       |11.0                      |17.5                      |177                           |7.9                        |11.1                       |16.9                       |177                            |0.00                    |0.00               |0.0                 |0                          |34                         |100                        |0.0                               |248.7                             |877.2                             |5968.7                            |

In [101]:
wdf2 = wdf.to_pandas()

In [102]:
wdf2.head()

,POSTAL_CODE,COUNTRY,DATE_VALID_STD,DOY_STD,MIN_TEMPERATURE_AIR_2M_F,AVG_TEMPERATURE_AIR_2M_F,MAX_TEMPERATURE_AIR_2M_F,MIN_TEMPERATURE_WETBULB_2M_F,AVG_TEMPERATURE_WETBULB_2M_F,MAX_TEMPERATURE_WETBULB_2M_F,...,TOT_PRECIPITATION_IN,TOT_SNOWFALL_IN,TOT_SNOWDEPTH_IN,MIN_CLOUD_COVER_TOT_PCT,AVG_CLOUD_COVER_TOT_PCT,MAX_CLOUD_COVER_TOT_PCT,MIN_RADIATION_SOLAR_TOTAL_WPM2,AVG_RADIATION_SOLAR_TOTAL_WPM2,MAX_RADIATION_SOLAR_TOTAL_WPM2,TOT_RADIATION_SOLAR_TOTAL_WPM2
0,71678,US,2021-06-24,175,72.0,82.7,92.8,70.0,75.4,78.4,...,0.0,0.0,0.0,0,22,85,0.0,288.4,911.3,6922.5
1,71701,US,2021-06-24,175,72.9,83.7,95.3,71.0,76.5,79.7,...,0.0,0.0,0.0,0,32,100,0.0,237.0,865.5,5686.7
2,71858,US,2021-06-24,175,73.4,83.8,93.6,72.1,76.2,78.6,...,0.0,0.0,0.0,0,23,97,0.0,274.1,874.3,6579.9
3,72085,US,2021-06-24,175,67.6,81.0,91.4,66.0,74.4,79.2,...,0.0,0.0,0.0,0,33,100,0.0,265.8,779.8,6379.2
4,72124,US,2021-06-24,175,71.8,82.7,92.3,69.2,75.3,79.2,...,0.0,0.0,0.0,0,37,100,0.0,252.4,873.3,6056.3

### Drop columns (like discount amount, etc)

In [103]:
df=df.drop(['ORDER_DISCOUNT_AMOUNT','ORDER_TAX_AMOUNT','ORDER_AMOUNT','PRICE','UNIT_PRICE','QUANTITY','MENU_ITEM_NAME','MENU_ITEM_ID','MARITAL_STATUS','GENDER','CHILDREN_COUNT','PHONE_NUMBER','E_MAIL','LAST_NAME','FIRST_NAME','CUSTOMER_ID','FRANCHISEE_FIRST_NAME','FRANCHISEE_LAST_NAME','FRANCHISE_ID','FRANCHISE_FLAG','LINE_NUMBER','ORDER_ID'])

### Transform order_ts to year, month, day, day of the week, hour, public holiday binary

In [104]:
df=df.withColumn("Month",F.month(df["ORDER_TS"]))
df=df.withColumn("DOW",F.dayofweek(df["ORDER_TS"]))
df=df.withColumn("Day",F.dayofmonth(df["ORDER_TS"]))
df=df.withColumn("Hour",F.hour(df["ORDER_TS"]))
df=df.withColumn("WOM", ((F.dayofmonth(F.col('ORDER_TS')) - 1) / 7 + 1).cast('integer'))

In [105]:
# Create public holiday column binary
public_holidays = [
    {'Month': 7, 'Day': 4, 'DOW': None, 'WOM': None},  # 4th of July
    {'Month': 12, 'Day': 24, 'DOW': None, 'WOM': None},  # Christmas Eve
    {'Month': 12, 'Day': 25, 'DOW': None, 'WOM': None},  # Christmas Day
    {'Month': 10, 'Day': None, 'DOW': '1', 'WOM': 2},  # Columbus Day (second Monday in October)
    {'Month': 6, 'Day': 19, 'DOW': None, 'WOM': None},  # Juneteenth
    {'Month': 9, 'Day': None, 'DOW': '1', 'WOM': 1},  # Labor Day (first Monday in September)
    {'Month': 1, 'Day': None, 'DOW': '1', 'WOM': 3},  # Martin Luther King, Jr. Day (third Monday in January)
    {'Month': 5, 'Day': None, 'DOW': '1', 'WOM': -1},  # Memorial Day (last Monday in May)
    {'Month': 1, 'Day': 1, 'DOW': None, 'WOM': None},  # New Year's Day
    {'Month': 12, 'Day': 31, 'DOW': None, 'WOM': None},  # New Year's Eve
    {'Month': 11, 'Day': None, 'DOW': '4', 'WOM': 4},  # Thanksgiving Day (fourth Thursday in November)
    {'Month': 11, 'Day': None, 'DOW': '3', 'WOM': 4},  # Thanksgiving Eve (fourth Wednesday in November)
    {'Month': 2, 'Day': 14, 'DOW': None, 'WOM': None},  # Valentine's Day
    {'Month': 11, 'Day': 11, 'DOW': None, 'WOM': None},  # Veterans Day
    {'Month': 10, 'Day': 31, 'DOW': None, 'WOM': None},  # Halloween
    {'Month': 3, 'Day': 17, 'DOW': None, 'WOM': None},  # St. Patrick's Day
    {'Month': 11, 'Day': 25, 'DOW': '5', 'WOM': None},  # Black Friday
    {'Month': 12, 'Day': 26, 'DOW': None, 'WOM': None},  # Boxing Day
]

In [106]:
from snowflake.snowpark.functions import udf
from snowflake.snowpark.types import IntegerType
'''def is_public_holiday(month, day, dow, wom):
    for holiday in public_holidays:
        if holiday['Month'] == month and holiday['DOW'] == dow and holiday['WOM'] == wom:
            if holiday['Day'] is None:
                return True
            elif holiday['Day'] == day:
                return True
    return False

session.sql("USE SCHEMA RAW_POS").collect()
@udf(session=session, name='public_holiday', input_types=[IntegerType(), IntegerType(), IntegerType(), IntegerType()], return_type=IntegerType(), is_permanent=False, replace=True)
def public_holiday(month: int, day: int, dow: int, wom: int) -> int:
    if is_public_holiday(month, day, dow, wom):
        return 1
    else:
        return 0

df=df.withColumn('PUBLIC_HOLIDAY', public_holiday(F.month(F.col('DATE')), F.dayofmonth(F.col('DATE')), F.dayofweek(F.col('DATE')), ((F.col('Day') - 1) / 7 + 1).cast('integer')))'''

from snowflake.snowpark.functions import col, when

# Initialize the 'PUBLIC_HOLIDAY' column to 0
df = df.withColumn('PUBLIC_HOLIDAY', F.lit(0))

# Iterate through the public_holidays list and update the 'PUBLIC_HOLIDAY' column
for h in public_holidays:
    df = df.withColumn(
        'PUBLIC_HOLIDAY',
        when(
            (F.month(F.col('DATE')) == h['Month']) &
            (F.dayofweek(F.col('DATE')) == h['DOW'] if h['DOW'] is not None else True) &
            (((F.col('Day') - 1) / 7 + 1).cast('integer') == h['WOM'] if h['WOM'] is not None else True) &
            (F.dayofmonth(F.col('DATE')) == h['Day'] if h['Day'] is not None else True),
            1
        ).otherwise(F.col('PUBLIC_HOLIDAY')))

## Grouping

In [107]:
df.show()

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"DATE"      |"TRUCK_ID"  |"ORDER_TS"           |"ORDER_DETAIL_ID"  |"TRUCK_BRAND_NAME"  |"MENU_TYPE"  |"PRIMARY_CITY"  |"REGION"  |"COUNTRY"      |"LOCATION_ID"  |"ORDER_TOTAL"  |"MONTH"  |"DOW"  |"DAY"  |"HOUR"  |"WOM"  |"PUBLIC_HOLIDAY"  |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2022-05-07  |17          |2022-05-07 19:16:49  |883147729          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |46.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:16:49  |883147730          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |46.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:16:49  |883147731          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |46.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:16:49  |883147732          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |46.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:20:49  |883147745          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |55.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:20:49  |883147746          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |55.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:20:49  |883147747          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |55.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:20:49  |883147749          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |55.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:20:49  |883147748          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |55.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:21:43  |883147753          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |54.0000        |5        |6      |7      |19      |2      |0                 |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [108]:
grouped_df = df.groupBy("DATE","TRUCK_ID","MONTH","HOUR","DOW","DAY","Menu_Type","LOCATION_ID","PUBLIC_HOLIDAY").agg(F.sum("ORDER_TOTAL"))

# Joining with weather data

In [109]:
connection_parameters = {
    "account": accountname,
    "user": username,
    "password": password,
    "role": "ACCOUNTADMIN",
    "database": "GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI",

    "warehouse": "HOL_WH"
}

wea_session = Session.builder.configs(connection_parameters).create()
wdf = wea_session.table('STANDARD_TILE.HISTORY_DAY')

In [110]:
wdf=wea_session.sql("select * From STANDARD_TILE.HISTORY_DAY")

In [111]:
print(type(wdf))
#print(type(semi_final_df))

<class 'snowflake.snowpark.dataframe.DataFrame'>

In [112]:
grouped_df.show()

---------------------------------------------------------------------------------------------------------------------------------------
|"DATE"      |"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"MENU_TYPE"     |"LOCATION_ID"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |
---------------------------------------------------------------------------------------------------------------------------------------
|2022-05-05  |65          |5        |10      |4      |5      |Ramen           |12058          |0                 |20461.5000          |
|2022-05-05  |65          |5        |22      |4      |5      |Ramen           |3280           |0                 |12095.7500          |
|2022-05-05  |66          |5        |11      |4      |5      |Grilled Cheese  |3245           |0                 |7303.0000           |
|2022-05-05  |66          |5        |16      |4      |5      |Grilled Cheese  |2173           |0                 |8848.0000           |
|2022-05-05  |67          |5        |12      |4      |5      |Vegetarian      |4092           |0                 |11536.0000          |
|2022-05-05  |68          |5        |15      |4      |5      |Crepes          |3908           |0                 |8798.0000           |
|2022-05-05  |69          |5        |10      |4      |5      |Ethiopian       |2593           |0                 |14670.0000          |
|2022-05-05  |69          |5        |14      |4      |5      |Ethiopian       |2593           |0                 |13470.0000          |
|2022-05-05  |69          |5        |19      |4      |5      |Ethiopian       |4026           |0                 |15373.0000          |
|2022-05-05  |70          |5        |13      |4      |5      |Hot Dogs        |8426           |0                 |14436.0000          |
---------------------------------------------------------------------------------------------------------------------------------------

In [113]:
wdf_re=wdf.with_column_renamed(col("DATE_VALID_STD"), "DATE")

In [114]:
sdf_loc = session.table('RAW_POS.Location_New')

In [115]:
sdf_loc_dr=sdf_loc.drop("PLACEKEY","ISO_COUNTRY_CODE")

In [116]:
sdf_loc_dr.show()

---------------------------------------------------------------------------------------------------------------------------------------------------------------
|"LOCATION_ID"  |"LOCATION"                                        |"CITY"  |"REGION"  |"COUNTRY"      |"LAT"               |"LONG"               |"ZIPCODE"  |
---------------------------------------------------------------------------------------------------------------------------------------------------------------
|1030           |University Of Colorado Museum Of Natural History  |Denver  |CO        |United States  |40.00768674326263   |-105.26970066129032  |80802      |
|1031           |Denver Technological Center                       |Denver  |CO        |United States  |39.62735682905758   |-104.91269066527825  |80237      |
|1032           |Heritage Club At Denver Tech Center               |Denver  |CO        |United States  |39.62526657316754   |-104.91238594440485  |80237      |
|1033           |Porter Wound Care Center                          |Denver  |CO        |United States  |39.671421009959225  |-104.97636575469211  |80210      |
|1034           |Emeritus at Highline                              |Denver  |CO        |United States  |39.68681241616432   |-104.89274135984651  |80247      |
|1035           |Cherry Creek Gun Club                             |Denver  |CO        |United States  |39.69212431173931   |-104.8771588467281   |80247      |
|1036           |The Courtyards at Mountain View                   |Denver  |CO        |United States  |39.69737086762524   |-104.89264470571358  |80247      |
|1037           |The Denver Hospice                                |Denver  |CO        |United States  |39.71958553918071   |-104.89179382614257  |80230      |
|1038           |Sandstone Care                                    |Denver  |CO        |United States  |39.67758633438455   |-104.93392167584601  |80222      |
|1039           |Serenity House Assisted Living Office             |Denver  |CO        |United States  |39.668469528717374  |-104.92850076530557  |80222      |
---------------------------------------------------------------------------------------------------------------------------------------------------------------

In [117]:
semi_final_df=grouped_df.join(sdf_loc_dr, grouped_df["LOCATION_ID"] == sdf_loc_dr["LOCATION_ID"])

In [118]:
semi_final_df.show()

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"DATE"      |"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"MENU_TYPE"   |"l_hiu2_LOCATION_ID"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"r_kjds_LOCATION_ID"  |"LOCATION"                   |"CITY"         |"REGION"  |"COUNTRY"      |"LAT"               |"LONG"              |"ZIPCODE"  |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2022-02-05  |62          |2        |20      |6      |5      |BBQ           |4111                  |0                 |20145.0000          |4111                  |Alcoholics Anonymous         |New York City  |NY        |United States  |40.74744522439124   |-73.9935797183396   |10001      |
|2022-02-05  |64          |2        |11      |6      |5      |Mac & Cheese  |8426                  |0                 |15383.0000          |8426                  |Drummers Grove               |New York City  |NY        |United States  |40.66063973710185   |-73.96514423381791  |11215      |
|2022-02-05  |65          |2        |14      |6      |5      |Ramen         |15126                 |0                 |12240.2500          |15126                 |St Nicholas Park             |New York City  |NY        |United States  |40.81740567396844   |-73.94918415988849  |10030      |
|2022-02-05  |65          |2        |20      |6      |5      |Ramen         |2296                  |0                 |20130.7500          |2296                  |Imported Foods               |New York City  |NY        |United States  |40.75463869167259   |-73.99294553139737  |10018      |
|2022-02-05  |67          |2        |10      |6      |5      |Vegetarian    |3008                  |0                 |14551.0000          |3008                  |Lulo Restaurant              |New York City  |NY        |United States  |40.855777227459605  |-73.92798471258929  |10040      |
|2022-02-05  |67          |2        |21      |6      |5      |Vegetarian    |15149                 |0                 |11593.0000          |15149                 |Fresh Creek Nature Preserve  |New York City  |NY        |United States  |40.64393588870993   |-73.88396778341095  |11236      |
|2022-02-05  |68          |2        |17      |6      |5      |Crepes        |2451                  |0                 |16595.0000          |2451                  |Mamak Cart                   |New York City  |NY        |United States  |40.7400323030105    |-73.9883970469128   |10010      |
|2022-02-05  |69          |2        |18      |6      |5      |Ethiopian     |2359                  |0                 |13924.0000          |2359                  |East Side Meat Corporation   |New York City  |NY        |United States  |40.7218381268811    |-73.9769885101504   |10009      |
|2022-02-05  |70          |2        |15      |6      |5      |Hot Dogs      |15213                 |0                 |7838.0000           |15213                 |I S 049 Bertha A Dreyfus     |New York City  |NY        |United States  |40.620892469454624  |-74.08039081143072  |10304      |
|2022-02-05  |70          |2        |17      |6      |5      |Hot Dogs      |15213                 |0                 |12216.0000          |15213                 |I S 049 Bertha A Dreyfus     |New York City  |NY        |United States  |40.620892469454624  |-74.08039081143072  |10304      |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [119]:
# # # # weather=wdf_re.to_pandas()
# weather=wdf_re.to_pandas()
# syntax=pd.io.sql.get_schema(weather, "weather_data")
# session.use_schema("ANALYTICS")
# session.sql(
    
#     syntax
# ).collect()
# session.write_pandas(
#     df=weather,
#     table_name="weather_data",
#     database="frostbyte_tasty_bytes",
#     schema="ANALYTICS",
#     quote_identifiers=False,
#     overwrite=True)

In [120]:
semi_final_df=semi_final_df.with_column_renamed(col("ZIPCODE"), "POSTAL_CODE")

In [121]:
type(wdf_re["DATE"])

snowflake.snowpark.column.Column

In [122]:
wdf = session.table('RAW_POS.weather_data')
wdf=wdf.select("POSTAL_CODE","DATE","COUNTRY","AVG_TEMPERATURE_AIR_2M_F","AVG_TEMPERATURE_HEATINDEX_2M_F","TOT_PRECIPITATION_IN","TOT_SNOWFALL_IN","TOT_SNOWDEPTH_IN","AVG_CLOUD_COVER_TOT_PCT")

In [123]:
final_df = semi_final_df.join(wdf, (semi_final_df["DATE"] == wdf["DATE"]) & (semi_final_df["POSTAL_CODE"] == wdf["POSTAL_CODE"])  )

In [124]:
session.use_schema("ANALYTICS")
final_df.write.save_as_table(table_name="sales_prediction", mode='overwrite')

## Merging

In [125]:
to_encode_df = session.table('ANALYTICS.SALES_PREDICTION')

In [126]:
to_encode_df.show()

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"l_g44h_DATE"  |"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"MENU_TYPE"  |"l_hiu2_LOCATION_ID"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"r_kjds_LOCATION_ID"  |"LOCATION"          |"CITY"         |"REGION"  |"l_g44h_COUNTRY"  |"LAT"              |"LONG"               |"l_g44h_POSTAL_CODE"  |"r_szdb_POSTAL_CODE"  |"r_szdb_DATE"  |"r_szdb_COUNTRY"  |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2021-10-22     |44          |10       |9       |5      |22     |Indian       |3003                  |0                 |12344.0000          |3003                  |Dragonfly Pavilion  |Seattle        |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2021-10-22     |US                |52.6                        |52.6                              |0.1                     |0.0                |0.0                 |94                         |
|2021-10-22     |44          |10       |10      |5      |22     |Indian       |3003                  |0                 |8574.0000           |3003                  |Dragonfly Pavilion  |Seattle        |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2021-10-22     |US                |52.6                        |52.6                              |0.1                     |0.0                |0.0                 |94                         |
|2021-10-22     |44          |10       |12      |5      |22     |Indian       |3003                  |0                 |17950.0000          |3003                  |Dragonfly Pavilion  |Seattle        |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2021-10-22     |US                |52.6                        |52.6                              |0.1                     |0.0                |0.0                 |94                         |
|2021-10-22     |44          |10       |13      |5      |22     |Indian       |3003                  |0                 |8024.0000           |3003                  |Dragonfly Pavilion  |Seattle        |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2021-10-22     |US                |52.6                        |52.6                              |0.1                     |0.0                |0.0                 |94                         |
|2021-10-22     |44          |10       |11      |5      |22     |Indian       |3003                  |0                 |8246.0000           |3003                  |Dragonfly Pavilion  |Seattle        |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2021-10-22     |US                |52.6                        |52.6                              |0.1                     |0.0                |0.0                 |94                         |
|2021-10-22     |44          |10       |14      |5      |22     |Indian       |3003                  |0                 |5644.0000           |3003                  |Dragonfly Pavilion  |Seattle        |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2021-10-22     |US                |52.6                        |52.6                              |0.1                     |0.0                |0.0                 |94                         |
|2021-08-18     |67          |8        |17      |3      |18     |Vegetarian   |2867                  |0                 |11225.0000          |2867                  |A Caring Hand       |New York City  |NY        |United States     |40.7795067390542   |-73.95323502613428   |10128                 |10128                 |2021-08-18     |US                |78.3                        |82.9                              |0.0                     |0.0                |0.0                 |97                         |
|2021-08-18     |67          |8        |21      |3      |18     |Vegetarian   |2867                  |0                 |12402.0000          |2867                  |A Caring Hand       |New York City  |NY        |United States     |40.7795067390542   |-73.95323502613428   |10128                 |10128                 |2021-08-18     |US                |78.3                        |82.9                              |0.0                     |0.0                |0.0                 |97                         |
|2021-08-18     |67          |8        |20      |3      |18     |Vegetarian   |2867                  |0                 |11967.0000          |2867                  |A Caring Hand       |New York City  |NY        |United States     |40.7795067390542   |-73.95323502613428   |10128                 |10128                 |2021-08-18     |US                |78.3                        |82.9                              |0.0                     |0.0                |0.0                 |97                         |
|2021-08-18     |67          |8        |18      |3      |18     |Vegetarian   |2867                  |0                 |12902.0000          |2867                  |A Caring Hand       |New York City  |NY        |United States     |40.7795067390542   |-73.95323502613428   |10128                 |10128                 |2021-08-18     |US                |78.3                        |82.9                              |0.0                     |0.0                |0.0                 |97                         |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [127]:
columns_to_drop = ['"r_sim4_LOCATION_ID"','"l_08qh_COUNTRY"','"l_08qh_POSTAL_CODE"','"r_c08p_DATE"','"r_c08p_COUNTRY"']
new_columns  = [c for c in to_encode_df.columns if c not in columns_to_drop]
dropped_df = to_encode_df.select(*new_columns)

In [128]:
connection_parameters = {
    "account": accountname,
    "user": username,
    "password": password,
    "role": "ACCOUNTADMIN",
    "database": "FROSTBYTE_TASTY_BYTE",

    "warehouse": "HOL_WH"
}

nt_session = Session.builder.configs(connection_parameters).create()
sales = nt_session.sql("Select * from ANALYTICS.DEMAND_FORECAST_TRAINING_Base")

In [129]:
sales.show()

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"DATE"      |"SHIFT"  |"PRIMARY_CITY"  |"LOCATION_ID"  |"MENU_TYPE"   |"MENU_ITEM_ID"  |"MONTH_OF_YEAR"  |"DAY_OF_WEEK"  |"UNIT_PRICE"  |"PREV_YEAR_MONTH_SALES_CITY"  |"PREV_YEAR_MONTH_SALES_LOCATION"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_ITEM"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |"DAY_OF_WEEK_AVG_CITY"  |"DAY_OF_WEEK_AVG_LOCATION"  |"DAY_OF_WEEK_AVG_CITY_MENU_ITEM"  |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"QUANTITY"  |"AVG_SALES_7D_LOCATION"  |"AVG_SALES_14D_LOCATION"  |"AVG_SALES_28D_LOCATION"  |"AVG_SALES_LOCATION"  |"AVG_SALES_7D_LOCATION_MENU_TYPE"  |"AVG_SALES_14D_LOCATION_MENU_TYPE"  |"AVG_SALES_28D_LOCATION_MENU_TYPE"  |"AVG_SALES_LOCATION_MENU_TYPE"  |"AVG_QUANTITY_7D_LOCATION_MENU_ITEM"  |"AVG_QUANTITY_14D_LOCATION_MENU_ITEM"  |"AVG_QUANTITY_28D_LOCATION_MENU_ITEM"  |"AVG_QUANTITY_LOCATION_MENU_ITEM"  |"AVG_SALES_7D_CITY"  |"AVG_SALES_14D_CITY"  |"AVG_SALES_28D_CITY"  |"AVG_SALES_CITY"  |"AVG_SALES_7D_CITY_MENU_TYPE"  |"AVG_SALES_14D_CITY_MENU_TYPE"  |"AVG_SALES_28D_CITY_MENU_TYPE"  |"AVG_SALES_CITY_MENU_TYPE"  |"AVG_QUANTITY_7D_CITY_MENU_ITEM"  |"AVG_QUANTITY_14D_CITY_MENU_ITEM"  |"AVG_QUANTITY_28D_CITY_MENU_ITEM"  |"AVG_QUANTITY_CITY_MENU_ITEM"  |"AVG_SALES_7D_MENU_TYPE"  |"AVG_SALES_14D_MENU_TYPE"  |"AVG_SALES_28D_MENU_TYPE"  |"AVG_SALES_MENU_TYPE"  |"AVG_QUANTITY_7D_MENU_ITEM"  |"AVG_QUANTITY_14D_MENU_ITEM"  |"AVG_QUANTITY_28D_MENU_ITEM"  |"AVG_QUANTITY_MENU_ITEM"  |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2021-11-14  |PM       |Cairo           |10565          |Ice Cream     |16              |11               |0              |3.0000        |1852815.00                    |12634.00                          |NULL                                    |NULL                                    |2307.47021              |723.16666                   |211.90000                         |744.64531                         |75          |NULL                     |NULL                      |NULL                      |11760.40000           |NULL                               |NULL                                |NULL                                |NULL                            |NULL                                  |NULL                                   |NULL                                   |NULL                               |130009.87500         |130621.46666          |130567.36206          |68499.19481       |6718.50000                     |7046.06666                      |6798.70689                      |6911.67808                  |63.250                            |66.666                             |65.551                             |65.849                         |174148.43750              |173495.50000               |173275.93103               |65292.88750            |1669.375                     |1680.666                      |1681.034                      |631.692                   |
|2022-10-12  |PM       |Madrid          |14384          |Chinese       |136             |10               |3              |3.0000        |8831702.00                    |NULL                              |16020.00                                |764333.00                               |3957.16633              |3556.75000                  |514.02564                         |4067.12691                        |142         |14822.00000              |14822.00000               |19284.00000               |23880.55882           |NULL                               |NULL                                |NULL                                |26277.00000                     |NULL                                  |NULL                                   |NULL                                   |166.000                            |427538.37500         |422779.20000          |420569.20689          |166542.07085      |26091.75000                    |25557.00000                     |25333.13793                     |24722.78710                 |188.875                           |182.133                            |181.034                            |174.580                        |583677.00000              |580978.33333               |581725.75862               |228003.59313           |4135.250                     |4096.600                      |4115.206                      |1613.867                  |
|2021-02-23  |AM       |Cape Town       |7470           |Hot Dogs      |101             |2                |2              |8.0000        |2536971.00                    |NULL                              |NULL                                    |NULL                                    |4060.36589              |NULL                        |11512.00000                       |6954.38016                        |1318        |NULL                     |NULL                      |NULL                      |22830.16666           |NULL                               |NULL                                |NULL                                |NULL                            |NULL                                  |NULL                                   |NULL                                   |NULL                               |311803.43750         |311132.26666          |312502.08620          |102960.96838      |43835.25000                    |43016.26666                     |43201.44827                     |42593.03703                 |1552.500                          |1493.866                           |1493.448                           |1475.407                       |211231.50000              |207337.73333               |209194.58620               |53477.35672            |7329.250                     |7184.533                      |7247.000                      |1854.024                  |
|2022-02-15  |PM       |Tokyo           |11864          |Poutine       |116             |2                |2              |3.0000        |3330447.00                    |NULL                              |NULL                                    |NULL                                    |4712.56042              |4521.66666                  |572.25000                         |5628.50000                        |214         |NULL                     |49933.25000               |41338.37500               |31199.39285           |NULL                               |NULL                                |NULL                                |NULL                            |NULL                                  |NULL                                   |NULL                                   |NULL                               |451249.34375         |451510.50000          |450678.46551          |161190.36411      |35811.87500                    |35598.06666                     |35578.00000                     |35626.02857                 |200.250                           |199.333                            |200.241                            |200.142                        |533181.62500              |535600.66666               |535037.37931               |260571.02872           |3039.625                     |3043.266                      |3028.827                      |1472.947                  |
|2022-05-04  |PM       |Cape Town       |7453           |BBQ           |25              |5                |3              |3.0000        |10756766.50                   |NULL                              |NULL                                    |NULL                                    |5225.27426              |6188.14285                  |569.60000                         |3736.19867                        |203         |50810.00000              |50810.00000               |37733.25000               |34060.45370           |NULL                               |NULL                                |NULL                                |NULL                            |NULL                                  |NULL                                   |NULL                                   |NULL                               |629837.28125         |628722.88333          |586445.78448          |221573.70391      |33218.25000                    |33585.73333                     |33840.24137                     |33808.57142                 |185.125                           |188.933                            |192.344                            |190.330                        |725658.37500              |724764.13333               |712518.17241               |264426.58029           |4099.875                     |4103.733                      |4033.827                      |1494.293                  |
|2021-05-22  |PM       |Vancouver       |3899           |Mac & Cheese  |42              |5                |6              |10.0000       |1117714.00                    |NULL                              |60300.00                                |208180.00                               |1436.30000              |979.15384                   |2335.00000                        |1346.61290                        |255         |NULL                     |NULL                      |NULL                      |7601.90000            |NULL                               |NULL                                |NULL                                |NULL                            |NULL                                  |NULL                                   |NULL                                   |NULL                               |100031.68750         |99985.80000           |102374.94827          |34905.97377       |8466.75000                     |8221.06666                      |8416.37931                      |6999.19066                  |247.125                           |240.000                            |245.344                            |201.586                        |292739.62500              |295078.06666               |295732.51724               |173550.96957           |8477.875                     |8500.266                      |8489.862                      |4987.920                  |
|2022-04-13  |PM       |Mumbai          |14070          |Crepes        |84              |4                |3              |2.0000        |7677970.50                    |NULL                              |12134.00                                |1030913.00                              |5754.72983              |4990.46666                  |402.02222                         |5671.39492                        |200         |NULL                     |NULL                      |NULL                      |39035.29166           |NULL                               |NULL                                |NULL                                |33927.00000                     |NULL                                  |NULL                                   |NULL                                   |195.000                            |384595.81250         |381516.90000          |381022.05172          |168666.19742      |33566.87500                    |33790.73333                     |34203.55172                     |34138.96546                 |196.250                           |199.466                            |203.551                            |203.230                        |594394.25000              |597222.66666               |592717.82758               |229685.25610           |3571.000                     |3575.733                      |3535.793                      |1367.530                  |
|2020-07-17  |PM       |Warsaw          |12227          |Chinese       |134             |7                |5              |2.0000        |577524.00                     |NULL                              |8122.00                                 |577524.00                               |3113.92298              |318.00000                   |259.69230                         |3089.82744                        |111         |NULL                     |NULL                      |NULL                      |NULL                  |NULL                               |NULL                                |NULL                                |NULL                            |NULL                                  |NULL                                   |NULL                                   |NULL                               |55277.50000          |52318.40000           |52607.27586           |30691.65454       |14878.37500                    |15075.80000                     |15457.37931                     |18113.38181                 |109.125                           |108.866                            |109.379                            |127.843                        |102341.25000              |98089.93333                |95859.44827                |53581.26363            |727.625                      |699.866                       |685.655                       |379.610                   |
|2021-08-23  |AM       |Mumbai          |13658          |Indian        |142             |8                |1              |18.0000       |5206545.50                    |78696.00                          |421254.00                               |1210086.00                              |5150.42682              |5898.63157                  |13965.04477                       |6695.43398                        |771         |NULL                     |NULL                      |NULL                      |34532.63636           |NULL                               |NULL                                |NULL                                |40177.80000                     |NULL                                  |NULL                                   |NULL                                   |766.000                            |219803.53125         |219819.43333          |219709.93103          |116749.75314      |40201.62500                    |40505.60000                     |40775.27586                     |40173.80377                 |763.375                           |773.066                            |780.689                            |775.326                        |496574.37500              |502887.40000               |507307.37931               |192281.68200           |9581.250                     |9719.600                      |9801.206                      |3712.288                  |
|2022-07-16  |AM       |Paris           |14229          |Gyros         |124             |7                |6              |2.0000        |4292238.00                    |18812.00                          |7244.00                                 |734619.00                               |3445.73458              |459.00000                   |270.11538                         |4443.59633                        |147         |NULL                     |8321.00000                |16331.50000               |18407.66666           |NULL                               |NULL                                |24342.00000                         |24342.00000                     |NULL                                  |NULL                                   |131.000                                |131.000                            |288919.96875         |285921.00000          |290984.10344          |157350.25117      |23173.75000                    |22642.60000                     |23430.10344                     |24622.04109                 |113.125                           |110.333                            |115.758                            |122.926                        |709366.50000              |705975.00000               |703650.20689               |414967.63088           |3586.500                     |3565.733                      |3545.551                      |2082.693                  |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [130]:
merge_df=sales.select( "DATE","LOCATION_ID" , "MENU_TYPE","DAY_OF_WEEK_AVG_CITY_MENU_TYPE","PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE")

In [131]:
mdf=merge_df.to_pandas()

In [132]:
# syntax=pd.io.sql.get_schema(mdf, "DEMAND_FORECAST_TRAINING_Base")
# session.use_schema("ANALYTICS")
# session.sql(

#     syntax
# ).collect()
# session.write_pandas(
#     df=mdf,
#     table_name="DEMAND_FORECAST_TRAINING_Base",
#     database="frostbyte_tasty_bytes",
#     schema="ANALYTICS",
#     quote_identifiers=False,
#     overwrite=True)

In [133]:
mdf=session.sql("Select * from ANALYTICS.DEMAND_FORECAST_TRAINING_BASE")

In [134]:
mdf.where(col("PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE").isNull()).count()

1888021

In [135]:
mdf.count()

3403151

In [136]:
mdf.show()

-------------------------------------------------------------------------------------------------------------------------
|"DATE"      |"LOCATION_ID"  |"MENU_TYPE"   |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |
-------------------------------------------------------------------------------------------------------------------------
|2021-01-04  |7365           |Ethiopian     |NULL                              |NULL                                    |
|2021-03-29  |9803           |Mac & Cheese  |1971.76056                        |NULL                                    |
|2021-02-19  |9078           |Tacos         |3061.29123                        |799330.5                                |
|2021-11-26  |12513          |Indian        |6702.0201                         |1196902.0                               |
|2021-03-20  |11007          |Crepes        |2897.72693                        |417552.0                                |
|2022-06-20  |3099           |Tacos         |2817.9315                         |NULL                                    |
|2020-11-19  |12204          |Tacos         |1602.97551                        |469471.5                                |
|2021-12-21  |8163           |Indian        |6039.34217                        |990694.0                                |
|2021-12-02  |2439           |Tacos         |143.35256                         |NULL                                    |
|2020-11-02  |15061          |Tacos         |731.24059                         |284096.5                                |
-------------------------------------------------------------------------------------------------------------------------

In [137]:
dropped_df.show()

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"l_g44h_DATE"  |"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"MENU_TYPE"   |"l_hiu2_LOCATION_ID"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"r_kjds_LOCATION_ID"  |"LOCATION"       |"CITY"   |"REGION"  |"l_g44h_COUNTRY"  |"LAT"              |"LONG"               |"l_g44h_POSTAL_CODE"  |"r_szdb_POSTAL_CODE"  |"r_szdb_DATE"  |"r_szdb_COUNTRY"  |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2021-10-25     |32          |10       |15      |1      |25     |BBQ           |5176                  |0                 |819.0000            |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |17      |1      |25     |BBQ           |5176                  |0                 |3012.0000           |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |19      |1      |25     |BBQ           |5176                  |0                 |7724.0000           |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |16      |1      |25     |BBQ           |5176                  |0                 |1513.0000           |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |18      |1      |25     |BBQ           |5176                  |0                 |3337.0000           |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |21      |1      |25     |BBQ           |5176                  |0                 |5933.0000           |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |22      |1      |25     |BBQ           |5176                  |0                 |99.0000             |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |20      |1      |25     |BBQ           |5176                  |0                 |7843.0000           |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-12-08     |19          |12       |9       |3      |8      |Mac & Cheese  |14950                 |0                 |4758.0000           |14950                 |Speer Blvd Park  |Denver   |CO        |United States     |39.75062334730824  |-105.00517561043424  |80217                 |80217                 |2021-12-08     |US                |44.2                        |44.2                              |0.0                     |0.0                |0.0                 |61                         |
|2021-12-08     |19          |12       |11      |3      |8      |Mac & Cheese  |14950                 |0                 |2312.0000           |14950                 |Speer Blvd Park  |Denver   |CO        |United States     |39.75062334730824  |-105.00517561043424  |80217                 |80217                 |2021-12-08     |US                |44.2                        |44.2                              |0.0                     |0.0                |0.0                 |61                         |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [139]:
merge_df=dropped_df.join(mdf, (dropped_df['"l_g44h_DATE"'] == mdf["DATE"])& (dropped_df['"MENU_TYPE"'] == mdf["MENU_TYPE"])& (dropped_df['"l_hiu2_LOCATION_ID"'] == mdf["Location_ID"]),"inner").drop('"l_g44h_DATE"').drop('"Date"').drop('"l_hiu2_LOCATION_ID"')

In [140]:
merge_df.show()

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"l_xdrx_MENU_TYPE"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"r_kjds_LOCATION_ID"  |"LOCATION"          |"CITY"   |"REGION"  |"l_g44h_COUNTRY"  |"LAT"              |"LONG"               |"l_g44h_POSTAL_CODE"  |"r_szdb_POSTAL_CODE"  |"r_szdb_DATE"  |"r_szdb_COUNTRY"  |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |"DATE"      |"LOCATION_ID"  |"r_dyy7_MENU_TYPE"  |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|31          |7        |14      |2      |12     |Ice Cream           |0                 |235.0000            |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |9       |2      |12     |Ice Cream           |0                 |3432.5000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |8       |2      |12     |Ice Cream           |0                 |2373.0000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |12      |2      |12     |Ice Cream           |0                 |3995.0000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |13      |2      |12     |Ice Cream           |0                 |3166.0000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |10      |2      |12     |Ice Cream           |0                 |1653.5000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |11      |2      |12     |Ice Cream           |0                 |2129.5000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126                 |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|44          |10       |21      |5      |8      |Indian              |0                 |12036.0000          |15088                 |Seacrest Park       |Seattle  |WA        |United States     |47.5887688561122   |-122.38090452834078  |98126                 |98126                 |2021-10-08     |US                |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |NULL                                    |
|44          |10       |17      |5      |8      |Indian              |0                 |14810.0000          |15088                 |Seacrest Park       |Seattle  |WA        |United States     |47.5887688561122   |-122.38090452834078  |98126                 |98126                 |2021-10-08     |US                |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |NULL                                    |
|44          |10       |16      |5      |8      |Indian              |0                 |8822.0000           |15088                 |Seacrest Park       |Seattle  |WA        |United States     |47.5887688561122   |-122.38090452834078  |98126                 |98126                 |2021-10-08     |US                |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |NULL                                    |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [141]:
merge_df = merge_df.withColumnRenamed('"l_xdrx_MENU_TYPE"','Menu_Type').withColumnRenamed('"l_g44h_POSTAL_CODE"','POSTAL_CODE')

In [142]:
merge_df=merge_df.drop('"l_xdrx_MENU_TYPE"')

In [143]:
merge_df.show()

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"MENU_TYPE"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"r_kjds_LOCATION_ID"  |"LOCATION"          |"CITY"   |"REGION"  |"l_g44h_COUNTRY"  |"LAT"              |"LONG"               |"POSTAL_CODE"  |"r_szdb_POSTAL_CODE"  |"r_szdb_DATE"  |"r_szdb_COUNTRY"  |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |"DATE"      |"LOCATION_ID"  |"r_dyy7_MENU_TYPE"  |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|31          |7        |14      |2      |12     |Ice Cream    |0                 |235.0000            |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |9       |2      |12     |Ice Cream    |0                 |3432.5000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |8       |2      |12     |Ice Cream    |0                 |2373.0000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |12      |2      |12     |Ice Cream    |0                 |3995.0000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |13      |2      |12     |Ice Cream    |0                 |3166.0000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |10      |2      |12     |Ice Cream    |0                 |1653.5000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |11      |2      |12     |Ice Cream    |0                 |2129.5000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|44          |10       |21      |5      |8      |Indian       |0                 |12036.0000          |15088                 |Seacrest Park       |Seattle  |WA        |United States     |47.5887688561122   |-122.38090452834078  |98126          |98126                 |2021-10-08     |US                |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |NULL                                    |
|44          |10       |17      |5      |8      |Indian       |0                 |14810.0000          |15088                 |Seacrest Park       |Seattle  |WA        |United States     |47.5887688561122   |-122.38090452834078  |98126          |98126                 |2021-10-08     |US                |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |NULL                                    |
|44          |10       |16      |5      |8      |Indian       |0                 |8822.0000           |15088                 |Seacrest Park       |Seattle  |WA        |United States     |47.5887688561122   |-122.38090452834078  |98126          |98126                 |2021-10-08     |US                |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |NULL                                    |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

## Null Encoding

In [144]:
nullColumns = []
numRows = merge_df.count()
for k in merge_df.columns:
    
    nullRows = merge_df.where(col(k).isNull()).count()
    columns=[k,nullRows]
    if nullRows>0:
        columns.append(merge_df.stat.approxQuantile(k,[0.5]))
    nullColumns.append(columns)

nullColumns
# ['D']

[['TRUCK_ID', 0],
 ['MONTH', 0],
 ['HOUR', 0],
 ['DOW', 0],
 ['DAY', 0],
 ['MENU_TYPE', 0],
 ['PUBLIC_HOLIDAY', 0],
 ['"SUM(ORDER_TOTAL)"', 0],
 ['"r_kjds_LOCATION_ID"', 0],
 ['LOCATION', 0],
 ['CITY', 0],
 ['REGION', 0],
 ['"l_g44h_COUNTRY"', 0],
 ['LAT', 0],
 ['LONG', 0],
 ['POSTAL_CODE', 0],
 ['"r_szdb_POSTAL_CODE"', 0],
 ['"r_szdb_DATE"', 0],
 ['"r_szdb_COUNTRY"', 0],
 ['AVG_TEMPERATURE_AIR_2M_F', 0],
 ['AVG_TEMPERATURE_HEATINDEX_2M_F', 0],
 ['TOT_PRECIPITATION_IN', 0],
 ['TOT_SNOWFALL_IN', 0],
 ['TOT_SNOWDEPTH_IN', 0],
 ['AVG_CLOUD_COVER_TOT_PCT', 0],
 ['DATE', 0],
 ['LOCATION_ID', 0],
 ['"r_dyy7_MENU_TYPE"', 0],
 ['DAY_OF_WEEK_AVG_CITY_MENU_TYPE', 186, [1683.1472034615383]],
 ['PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE', 10921, [291685.22222222225]]]

In [145]:
dropped_df=merge_df.na.fill({'DAY_OF_WEEK_AVG_CITY_MENU_TYPE': 1683.1472034615383, 'PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE': 292095.2258064516})

In [146]:
nullColumns = []
numRows = dropped_df.count()
for k in dropped_df.columns:
    
    nullRows = dropped_df.where(col(k).isNull()).count()
    columns=[k,nullRows]
    if nullRows>0:
        columns.append(dropped_df.stat.approxQuantile(k,[0.5]))
    nullColumns.append(columns)

nullColumns
# ['D']

[['TRUCK_ID', 0],
 ['MONTH', 0],
 ['HOUR', 0],
 ['DOW', 0],
 ['DAY', 0],
 ['MENU_TYPE', 0],
 ['PUBLIC_HOLIDAY', 0],
 ['"SUM(ORDER_TOTAL)"', 0],
 ['"r_kjds_LOCATION_ID"', 0],
 ['LOCATION', 0],
 ['CITY', 0],
 ['REGION', 0],
 ['"l_g44h_COUNTRY"', 0],
 ['LAT', 0],
 ['LONG', 0],
 ['POSTAL_CODE', 0],
 ['"r_szdb_POSTAL_CODE"', 0],
 ['"r_szdb_DATE"', 0],
 ['"r_szdb_COUNTRY"', 0],
 ['AVG_TEMPERATURE_AIR_2M_F', 0],
 ['AVG_TEMPERATURE_HEATINDEX_2M_F', 0],
 ['TOT_PRECIPITATION_IN', 0],
 ['TOT_SNOWFALL_IN', 0],
 ['TOT_SNOWDEPTH_IN', 0],
 ['AVG_CLOUD_COVER_TOT_PCT', 0],
 ['DATE', 0],
 ['LOCATION_ID', 0],
 ['"r_dyy7_MENU_TYPE"', 0],
 ['DAY_OF_WEEK_AVG_CITY_MENU_TYPE', 0],
 ['PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE', 0]]

In [147]:
merge_df.count()

23566


### Encoding

In [148]:


dropped_df.show()

columns = dropped_df.columns

# Iterate over the columns and count the number of unique values
unique_counts = {}
for column in columns:
    unique_counts[column] = dropped_df.select(column).distinct().count()

# Print the unique counts for each column
for column, count in unique_counts.items():
    print(f"Column '{column}': {count}")

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"MENU_TYPE"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"r_kjds_LOCATION_ID"  |"LOCATION"          |"CITY"   |"REGION"  |"l_g44h_COUNTRY"  |"LAT"              |"LONG"               |"POSTAL_CODE"  |"r_szdb_POSTAL_CODE"  |"r_szdb_DATE"  |"r_szdb_COUNTRY"  |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |"DATE"      |"LOCATION_ID"  |"r_dyy7_MENU_TYPE"  |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|31          |7        |14      |2      |12     |Ice Cream    |0                 |235.0000            |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |9       |2      |12     |Ice Cream    |0                 |3432.5000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |8       |2      |12     |Ice Cream    |0                 |2373.0000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |12      |2      |12     |Ice Cream    |0                 |3995.0000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |13      |2      |12     |Ice Cream    |0                 |3166.0000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |10      |2      |12     |Ice Cream    |0                 |1653.5000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |11      |2      |12     |Ice Cream    |0                 |2129.5000           |3003                  |Dragonfly Pavilion  |Seattle  |WA        |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|44          |10       |21      |5      |8      |Indian       |0                 |12036.0000          |15088                 |Seacrest Park       |Seattle  |WA        |United States     |47.5887688561122   |-122.38090452834078  |98126          |98126                 |2021-10-08     |US                |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |292095.2258064516                       |
|44          |10       |17      |5      |8      |Indian       |0                 |14810.0000          |15088                 |Seacrest Park       |Seattle  |WA        |United States     |47.5887688561122   |-122.38090452834078  |98126          |98126                 |2021-10-08     |US                |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |292095.2258064516                       |
|44          |10       |16      |5      |8      |Indian       |0                 |8822.0000           |15088                 |Seacrest Park       |Seattle  |WA        |United States     |47.5887688561122   |-122.38090452834078  |98126          |98126                 |2021-10-08     |US                |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |292095.2258064516                       |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Column 'TRUCK_ID': 45
Column 'MONTH': 12
Column 'HOUR': 15
Column 'DOW': 7
Column 'DAY': 31
Column 'MENU_TYPE': 15
Column 'PUBLIC_HOLIDAY': 2
Column '"SUM(ORDER_TOTAL)"': 3248
Column '"r_kjds_LOCATION_ID"': 16
Column 'LOCATION': 16
Column 'CITY': 3
Column 'REGION': 3
Column '"l_g44h_COUNTRY"': 1
Column 'LAT': 14
Column 'LONG': 14
Column 'POSTAL_CODE': 4
Column '"r_szdb_POSTAL_CODE"': 4
Column '"r_szdb_DATE"': 338
Column '"r_szdb_COUNTRY"': 1
Column 'AVG_TEMPERATURE_AIR_2M_F': 312
Column 'AVG_TEMPERATURE_HEATINDEX_2M_F': 320
Column 'TOT_PRECIPITATION_IN': 67
Column 'TOT_SNOWFALL_IN': 16
Column 'TOT_SNOWDEPTH_IN': 26
Column 'AVG_CLOUD_COVER_TOT_PCT': 100
Column 'DATE': 338
Column 'LOCATION_ID': 16
Column '"r_dyy7_MENU_TYPE"': 15
Column 'DAY_OF_WEEK_AVG_CITY_MENU_TYPE': 3426
Column 'PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE': 231

In [149]:
categoricalColumns = ['MENU_TYPE', 'LOCATION', 'CITY', 'REGION']

In [150]:
def one_hot_encode_columns(df, column_names):
    encoded_df = df
    
    for column_name in column_names:
        unique_values = [row[column_name] for row in df.select(column_name).distinct().collect()]
        
        # Create a new column for each unique value and perform one-hot encoding
        for value in unique_values:
            encoded_column_name = f"{column_name}_{value}_encoded"
            encoded_df = encoded_df.withColumn(encoded_column_name, F.when(F.col(column_name) == value, 1).otherwise(0))
    
    
    return encoded_df

In [151]:
encoded_df = one_hot_encode_columns(dropped_df, categoricalColumns)

In [152]:
final_df = encoded_df.drop(*categoricalColumns)

In [153]:
final_df.show()

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"r_kjds_LOCATION_ID"  |"l_g44h_COUNTRY"  |"LAT"              |"LONG"               |"POSTAL_CODE"  |"r_szdb_POSTAL_CODE"  |"r_szdb_DATE"  |"r_szdb_COUNTRY"  |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |"DATE"      |"LOCATION_ID"  |"r_dyy7_MENU_TYPE"  |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |"MENU_TYPE_BBQ_ENCODED"  |"MENU_TYPE_Ice Cream_encoded"  |"MENU_TYPE_GYROS_ENCODED"  |"MENU_TYPE_CREPES_ENCODED"  |"MENU_TYPE_SANDWICHES_ENCODED"  |"MENU_TYPE_Hot Dogs_encoded"  |"MENU_TYPE_Mac & Cheese_encoded"  |"MENU_TYPE_Grilled Cheese_encoded"  |"MENU_TYPE_CHINESE_ENCODED"  |"MENU_TYPE_TACOS_ENCODED"  |"MENU_TYPE_ETHIOPIAN_ENCODED"  |"MENU_TYPE_VEGETARIAN_ENCODED"  |"MENU_TYPE_INDIAN_ENCODED"  |"MENU_TYPE_POUTINE_ENCODED"  |"MENU_TYPE_RAMEN_ENCODED"  |"LOCATION_Orchard Street Ravine_encoded"  |"LOCATION_Great Kills Park Hillcrest_encoded"  |"LOCATION_Centennial Gardens_encoded"  |"LOCATION_Meril Gardens_encoded"  |"LOCATION_Inspir Carnegie Hill_encoded"  |"LOCATION_Dragonfly Pavilion_encoded"  |"LOCATION_Lucy's Whey_encoded"  |"LOCATION_York Playground_encoded"  |"LOCATION_Budget Blinds of West Seattle & Centr...  |"LOCATION_The Jewish Museum_encoded"  |"LOCATION_Dribbl Basketball_encoded"  |"LOCATION_Seacrest Park_encoded"  |"LOCATION_Emeritus at West Seattle_encoded"  |"LOCATION_Speer Blvd Park_encoded"  |"LOCATION_Ball arena formerly Pepsi Center_enco...  |"LOCATION_A Caring Hand_encoded"  |"CITY_SEATTLE_ENCODED"  |"CITY_DENVER_ENCODED"  |"CITY_New York City_encoded"  |"REGION_NY_ENCODED"  |"REGION_CO_ENCODED"  |"REGION_WA_ENCODED"  |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|31          |7        |14      |2      |12     |0                 |235.0000            |3003                  |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                           |0                            |0                          |0                                         |0                                              |0                                      |0                                 |0                                        |1                                      |0                               |0                                   |0                                                   |0                                     |0                                     |0                                 |0                                            |0                                   |0                                                   |0                                 |1                       |0                      |0                             |0                    |0                    |1                    |
|31          |7        |9       |2      |12     |0                 |3432.5000           |3003                  |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                           |0                            |0                          |0                                         |0                                              |0                                      |0                                 |0                                        |1                                      |0                               |0                                   |0                                                   |0                                     |0                                     |0                                 |0                                            |0                                   |0                                                   |0                                 |1                       |0                      |0                             |0                    |0                    |1                    |
|31          |7        |8       |2      |12     |0                 |2373.0000           |3003                  |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                           |0                            |0                          |0                                         |0                                              |0                                      |0                                 |0                                        |1                                      |0                               |0                                   |0                                                   |0                                     |0                                     |0                                 |0                                            |0                                   |0                                                   |0                                 |1                       |0                      |0                             |0                    |0                    |1                    |
|31          |7        |12      |2      |12     |0                 |3995.0000           |3003                  |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                           |0                            |0                          |0                                         |0                                              |0                                      |0                                 |0                                        |1                                      |0                               |0                                   |0                                                   |0                                     |0                                     |0                                 |0                                            |0                                   |0                                                   |0                                 |1                       |0                      |0                             |0                    |0                    |1                    |
|31          |7        |13      |2      |12     |0                 |3166.0000           |3003                  |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                           |0                            |0                          |0                                         |0                                              |0                                      |0                                 |0                                        |1                                      |0                               |0                                   |0                                                   |0                                     |0                                     |0                                 |0                                            |0                                   |0                                                   |0                                 |1                       |0                      |0                             |0                    |0                    |1                    |
|31          |7        |10      |2      |12     |0                 |1653.5000           |3003                  |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                           |0                            |0                          |0                                         |0                                              |0                                      |0                                 |0                                        |1                                      |0                               |0                                   |0                                                   |0                                     |0                                     |0                                 |0                                            |0                                   |0                                                   |0                                 |1                       |0                      |0                             |0                    |0                    |1                    |
|31          |7        |11      |2      |12     |0                 |2129.5000           |3003                  |United States     |47.56624749575556  |-122.36866268608073  |98126          |98126                 |2022-07-12     |US                |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                           |0                            |0                          |0                                         |0                                              |0                                      |0                                 |0                                        |1                                      |0                               |0                                   |0                                                   |0                                     |0                                     |0                                 |0                                            |0                                   |0                                                   |0                                 |1                       |0                      |0                             |0                    |0                    |1                    |
|44          |10       |21      |5      |8      |0                 |12036.0000          |15088                 |United States     |47.5887688561122   |-122.38090452834078  |98126          |98126                 |2021-10-08     |US                |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |292095.2258064516                       |0                        |0                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |1                           |0                            |0                          |0                                         |0                                              |0                                      |0                                 |0                                        |0                                      |0                               |0                                   |0                                                   |0                                     |0                                     |1                                 |0                                            |0                                   |0                                                   |0                                 |1                       |0                      |0                             |0                    |0                    |1                    |

In [154]:
X_final=final_df[['TRUCK_ID',"MONTH",'HOUR','DOW','DAY','PUBLIC_HOLIDAY',"SUM(ORDER_TOTAL)",'LOCATION_ID','LAT','LONG','AVG_TEMPERATURE_AIR_2M_F',"AVG_TEMPERATURE_HEATINDEX_2M_F","TOT_PRECIPITATION_IN","TOT_SNOWFALL_IN","TOT_SNOWDEPTH_IN","AVG_CLOUD_COVER_TOT_PCT","DAY_OF_WEEK_AVG_CITY_MENU_TYPE","PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE" ]]

In [155]:
X_final.show()

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"LOCATION_ID"  |"LAT"              |"LONG"               |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|31          |7        |14      |2      |12     |0                 |235.0000            |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|31          |7        |9       |2      |12     |0                 |3432.5000           |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|31          |7        |8       |2      |12     |0                 |2373.0000           |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|31          |7        |12      |2      |12     |0                 |3995.0000           |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|31          |7        |13      |2      |12     |0                 |3166.0000           |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|31          |7        |10      |2      |12     |0                 |1653.5000           |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|31          |7        |11      |2      |12     |0                 |2129.5000           |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|44          |10       |21      |5      |8      |0                 |12036.0000          |15088          |47.5887688561122   |-122.38090452834078  |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |4929.11111                        |292095.2258064516                       |
|44          |10       |17      |5      |8      |0                 |14810.0000          |15088          |47.5887688561122   |-122.38090452834078  |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |4929.11111                        |292095.2258064516                       |
|44          |10       |16      |5      |8      |0                 |8822.0000           |15088          |47.5887688561122   |-122.38090452834078  |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |4929.11111                        |292095.2258064516                       |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [156]:
session.use_schema("ANALYTICS")
X_final.write.save_as_table(table_name="Encoded_Data", mode='overwrite')

In [157]:
X_final=X_final.to_pandas()

In [158]:
columns_not_to_scale=["TRUCK_ID","MONTH","HOUR","DOW","DAY","PUBLIC_HOLIDAY","LOCATION_ID","LAT","LONG","SUM(ORDER_TOTAL)"]     

cat_col = [i for i in X_final.columns if i not in columns_not_to_scale]

In [159]:
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, MaxAbsScaler
scaler=StandardScaler()
scaler.fit(X_final)
X_final_scaled = X_final.copy()
X_final_scaled[cat_col] = StandardScaler().fit_transform(X_final_scaled[cat_col])

In [160]:

y_final=final_df[['SUM(ORDER_TOTAL)']]
y_final=y_final.to_pandas()
y_final=pd.DataFrame(y_final,columns=y_final.columns)

In [161]:
X_final_scaled.head()

,TRUCK_ID,MONTH,HOUR,DOW,DAY,PUBLIC_HOLIDAY,SUM(ORDER_TOTAL),LOCATION_ID,LAT,LONG,AVG_TEMPERATURE_AIR_2M_F,AVG_TEMPERATURE_HEATINDEX_2M_F,TOT_PRECIPITATION_IN,TOT_SNOWFALL_IN,TOT_SNOWDEPTH_IN,AVG_CLOUD_COVER_TOT_PCT,DAY_OF_WEEK_AVG_CITY_MENU_TYPE,PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE
0,33,12,15,5,24,1,1596.0,2290,47.561638,-122.376698,-1.370498,-1.352155,1.17069,-0.111192,-0.199874,1.302848,-0.841069,-0.593733
1,33,12,21,5,24,1,9365.5,2290,47.561638,-122.376698,-1.370498,-1.352155,1.17069,-0.111192,-0.199874,1.302848,-0.841069,-0.593733
2,33,12,19,5,24,1,4939.0,2290,47.561638,-122.376698,-1.370498,-1.352155,1.17069,-0.111192,-0.199874,1.302848,-0.841069,-0.593733
3,33,12,16,5,24,1,1017.0,2290,47.561638,-122.376698,-1.370498,-1.352155,1.17069,-0.111192,-0.199874,1.302848,-0.841069,-0.593733
4,33,12,17,5,24,1,3433.0,2290,47.561638,-122.376698,-1.370498,-1.352155,1.17069,-0.111192,-0.199874,1.302848,-0.841069,-0.593733

In [162]:
#sum()

In [163]:
# syntax=pd.io.sql.get_schema(X_final_scaled, "Sales_Forecaster_Train_Date")
# session.use_schema("ANALYTICS")

# session.sql(

#     syntax
# )

In [164]:
import math

In [165]:
X_final_scaled["SUM(ORDER_TOTAL)"] = X_final_scaled["SUM(ORDER_TOTAL)"].apply(lambda x: round(x, 2))

In [166]:
X_final_scaled["AVG_TEMPERATURE_AIR_2M_F"].dtypes

dtype('float64')

In [167]:
X_final_scaled.rename(columns={"SUM(ORDER_TOTAL)": "Profit"},inplace=True)

In [14]:
session.write_pandas(
    df=X_final_scaled,
    table_name="Sales_Forecast_Training_Data",
    database="FROSTBYTE_TASTY_BYTES",
    schema="ANALYTICS",
    quote_identifiers=False,
    overwrite=True
)

NameError: name 'X_final_scaled' is not defined

## Machine Learning Modelling

In [6]:
session.use_schema("ANALYTICS")
X_final_scaled=session.sql("Select * from Sales_Forecast_Training_Data").to_pandas()

In [7]:
X_final_scaled

,TRUCK_ID,MONTH,HOUR,DOW,DAY,PUBLIC_HOLIDAY,PROFIT,LOCATION_ID,LAT,LONG,AVG_TEMPERATURE_AIR_2M_F,AVG_TEMPERATURE_HEATINDEX_2M_F,TOT_PRECIPITATION_IN,TOT_SNOWFALL_IN,TOT_SNOWDEPTH_IN,AVG_CLOUD_COVER_TOT_PCT,DAY_OF_WEEK_AVG_CITY_MENU_TYPE,PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE
0,33,12,15,5,24,1,1596.0,2290,47.561638,-122.376698,-1.370498,-1.352155,1.17069,-0.111192,-0.199874,1.302848,-0.841069,-0.593733
1,33,12,21,5,24,1,9365.5,2290,47.561638,-122.376698,-1.370498,-1.352155,1.17069,-0.111192,-0.199874,1.302848,-0.841069,-0.593733
2,33,12,19,5,24,1,4939.0,2290,47.561638,-122.376698,-1.370498,-1.352155,1.17069,-0.111192,-0.199874,1.302848,-0.841069,-0.593733
3,33,12,16,5,24,1,1017.0,2290,47.561638,-122.376698,-1.370498,-1.352155,1.17069,-0.111192,-0.199874,1.302848,-0.841069,-0.593733
4,33,12,17,5,24,1,3433.0,2290,47.561638,-122.376698,-1.370498,-1.352155,1.17069,-0.111192,-0.199874,1.302848,-0.841069,-0.593733
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23561,37,2,13,0,6,0,2399.0,2290,47.561638,-122.376698,-1.154850,-1.142405,-0.43925,-0.111192,-0.199874,0.675549,-0.786248,-0.384552
23562,37,2,9,0,6,0,6356.0,2290,47.561638,-122.376698,-1.154850,-1.142405,-0.43925,-0.111192,-0.199874,0.675549,-0.786248,-0.384552
23563,37,2,10,0,6,0,3073.0,2290,47.561638,-122.376698,-1.154850,-1.142405,-0.43925,-0.111192,-0.199874,0.675549,-0.786248,-0.384552
23564,37,2,12,0,6,0,6043.0,2290,47.561638,-122.376698,-1.154850,-1.142405,-0.43925,-0.111192,-0.199874,0.675549,-0.786248,-0.384552
23565,37,2,14,0,6,0,3327.0,2290,47.561638,-122.376698,-1.154850,-1.142405,-0.43925,-0.111192,-0.199874,0.675549,-0.786248,-0.384552

In [171]:
X_final_scaled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23566 entries, 0 to 23565
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   TRUCK_ID                              23566 non-null  int8
 1   MONTH                                 23566 non-null  int8
 2   HOUR                                  23566 non-null  int8
 3   DOW                                   23566 non-null  int8
 4   DAY                                   23566 non-null  int8
 5   PUBLIC_HOLIDAY                        23566 non-null  int8
 6   PROFIT                                23566 non-null  float64
 7   LOCATION_ID                           23566 non-null  int16
 8   LAT                                   23566 non-null  float64
 9   LONG                                  23566 non-null  float64
 10  AVG_TEMPERATURE_AIR_2M_F              23566 non-null  float64
 11  AVG_TEMPERATURE_HEATINDEX_2M_F        23566 non-null  float64
 12  TOT_PRECIPITATION_IN                  23566 non-null  float64
 13  TOT_SNOWFALL_IN                       23566 non-null  float64
 14  TOT_SNOWDEPTH_IN                      23566 non-null  float64
 15  AVG_CLOUD_COVER_TOT_PCT               23566 non-null  float64
 16  DAY_OF_WEEK_AVG_CITY_MENU_TYPE        23566 non-null  float64
 17  PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE  23566 non-null  float64
dtypes: float64(11), int16(1), int8(6)
memory usage: 2.2 MB

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import math

# Split the dataset into features (X) and target (y)
X = X_final_scaled.drop("PROFIT",axis=1)
y = X_final_scaled["PROFIT"]

# Split the dataset into training and testing datasets
X_train, X_holdout_test, y_train, y_holdout_test = train_test_split(X, y, test_size=0.4, random_state=42)
X_holdout, X_test, y_holdout, y_test = train_test_split(X_holdout_test, y_holdout_test, test_size=0.2, random_state=42)

In [173]:
from lightgbm import LGBMRegressor
lgbm = LGBMRegressor()
lgbm.fit(X_train, y_train)

LGBMRegressor()

In [178]:
print('Train MSE is: ', mean_squared_error(lgbm.predict(X_train), y_train))
print('Test MSE is: ', mean_squared_error(lgbm.predict(X_test), y_test))
print()
print('Train RMSE is: ',  math.sqrt(mean_squared_error(lgbm.predict(X_train), y_train)))
print('Test RMSE is: ', math.sqrt(mean_squared_error(lgbm.predict(X_test), y_test)))
print()
print('Train MAE is: ', mean_absolute_error(lgbm.predict(X_train), y_train))
print('Test MAE is: ', mean_absolute_error(lgbm.predict(X_test), y_test))
print()
print('Train R2 is: ', r2_score(lgbm.predict(X_train), y_train))
print('Test R2 is: ', r2_score(lgbm.predict(X_test), y_test))

Train MSE is:  2014136.3855472703
Test MSE is:  2289623.987367086

Train RMSE is:  1419.2027288401296
Test RMSE is:  1513.150351870919

Train MAE is:  1063.968459036136
Test MAE is:  1105.815378228909

Train R2 is:  0.9527253423956941
Test R2 is:  0.9448532150166624

In [175]:
from xgboost import XGBRegressor
xgb = XGBRegressor()
xgb.fit(X_train, y_train)

c:\Users\Jammie99\anaconda3\envs\pysnowpark\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
c:\Users\Jammie99\anaconda3\envs\pysnowpark\lib\site-packages\xgboost\data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=4,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [179]:
print('Train MSE is: ', mean_squared_error(xgb.predict(X_train), y_train))
print('Test MSE is: ', mean_squared_error(xgb.predict(X_test), y_test))
print()
print('Train RMSE is: ',  math.sqrt(mean_squared_error(xgb.predict(X_train), y_train)))
print('Test RMSE is: ', math.sqrt(mean_squared_error(xgb.predict(X_test), y_test)))
print()
print('Train MAE is: ', mean_absolute_error(xgb.predict(X_train), y_train))
print('Test MAE is: ', mean_absolute_error(xgb.predict(X_test), y_test))
print()
print('Train R2 is: ', r2_score(xgb.predict(X_train), y_train))
print('Test R2 is: ', r2_score(xgb.predict(X_test), y_test))

Train MSE is:  771526.7620708488
Test MSE is:  1236772.561729723

Train RMSE is:  878.3659613571377
Test RMSE is:  1112.102765813359

Train MAE is:  641.8070704684887
Test MAE is:  777.6534032164298

Train R2 is:  0.9827021720783029
Test R2 is:  0.9715130780191024

## Fine-tuned XGBoost

In [ ]:
xgb = XGBRegressor(learning_rate= 0.04, max_depth= 10, n_estimators= 1700, subsample= 0.9)
xgb.fit(X_train, y_train)
print('Train MSE is: ', mean_squared_error(xgb.predict(X_train), y_train))
print('Test MSE is: ', mean_squared_error(xgb.predict(X_test), y_test))
print()
print('Train RMSE is: ',  math.sqrt(mean_squared_error(xgb.predict(X_train), y_train)))
print('Test RMSE is: ', math.sqrt(mean_squared_error(xgb.predict(X_test), y_test)))
print()
print('Train MAE is: ', mean_absolute_error(xgb.predict(X_train), y_train))
print('Test MAE is: ', mean_absolute_error(xgb.predict(X_test), y_test))
print()
print('Train R2 is: ', r2_score(xgb.predict(X_train), y_train))
print('Test R2 is: ', r2_score(xgb.predict(X_test), y_test))

In [18]:
from sklearn. ensemble import RandomForestRegressor, BaggingRegressor, AdaBoostRegressor, VotingRegressor

# Build Random Forest Model and Evaluate both training and testing accuracy
rf = RandomForestRegressor(n_estimators=40)
rf.fit(X_train,y_train)

RandomForestRegressor(n_estimators=40)

In [20]:

print('Train MSE is: ', mean_squared_error(rf.predict(X_train), y_train))
print('Test MSE is: ', mean_squared_error(rf.predict(X_test), y_test))
print()
print('Train RMSE is: ',  math.sqrt(mean_squared_error(rf.predict(X_train), y_train)))
print('Test RMSE is: ', math.sqrt(mean_squared_error(rf.predict(X_test), y_test)))
print()
print('Train MAE is: ', mean_absolute_error(rf.predict(X_train), y_train))
print('Test MAE is: ', mean_absolute_error(rf.predict(X_test), y_test))
print()
print('Train R2 is: ', r2_score(rf.predict(X_train), y_train))
print('Test R2 is: ', r2_score(rf.predict(X_test), y_test))

Train MSE is:  79323.84858511087
Test MSE is:  428601.3704179439

Train RMSE is:  281.6448980278373
Test RMSE is:  654.676538771586

Train MAE is:  130.88767548978004
Test MAE is:  325.33809981442204

Train R2 is:  0.9982722052471262
Test R2 is:  0.9903412496609059

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score, cross_validate
import seaborn as sns
import scipy.stats as stats

In [24]:
def cvr2(model): #Cross Validation scores function
    results  = cross_validate(model, X_train, y_train, scoring='r2', cv=5, return_train_score = True)
    print('train_score: ', results['train_score'])
    print('test_score: ', results['test_score'], '\n')

    print('cross val training R^2 value is: ', sum(results['train_score'])/len(results['train_score']))
    print('cross val testing R^2 value is: ', sum(results['test_score'])/len(results['test_score']))

def cvrm(model): #Cross Validation scores function
    results  = cross_validate(model, X_train, y_train, scoring='neg_root_mean_squared_error', cv=5, return_train_score = True)
    print('train_score: ', results['train_score'])
    print('test_score: ', results['test_score'], '\n')

    print('cross val training rmse is:', -(sum(results['train_score'])/len(results['train_score'])))
    print('cross val testing rmse is:', -(sum(results['test_score'])/len(results['test_score'])))
    
def cvm(model): #Cross Validation scores function
    results  = cross_validate(model, X_train, y_train, scoring='neg_mean_absolute_error', cv=5, return_train_score = True)
    print('train_score: ', results['train_score'])
    print('test_score: ', results['test_score'], '\n')

    print('cross val training mae is:', (-(sum(results['train_score'])/len(results['train_score']))))
    print('cross val testing mae is:', (-(sum(results['test_score'])/len(results['test_score']))))
    
def cv(model):
    print("R^2 value: ")
    cvr2(model)
    print(" \nRmse: ")
    cvrm(model)
    print(" \nMae: ")
    cvm(model)

In [25]:
rf = RandomForestRegressor()

param_grid = {"n_estimators"      : [10,30,50, 100, 200],
              'ccp_alpha': [0.0, 0.1, 0.2],
              'criterion': ['mse', 'absolute_error'],
#             "max_features"      : ["auto", "sqrt", "log2"],
#              "min_samples_leaf" : [1, 5, 10],
#             "min_samples_split" : [2, 4, 10, 12, 16], 
#              "max_leaf_nodes":[None,10,20,30,40,50,60,70,80,90],
              'max_depth' : [5, 25, 125, 525, 1225]
             }

gs = GridSearchCV(rf, param_grid=param_grid, scoring='r2', cv= 3, n_jobs=-1, verbose = 2)
# cv: number of partitions for cross validation
# n_jobs: number of jobs to run in parallel, -1 means using all processors

gs = gs.fit(X_train, y_train)

print(gs.best_score_)
print(gs.best_params_)

Fitting 3 folds for each of 150 candidates, totalling 450 fits

In [ ]:
rf = RandomForestRegressor(ccp_alpha = 0.0, criterion='mse',max_depth = 525, n_estimators = 200)
rf.fit(X_train, y_train)

cv(rf)

In [15]:
from sklearn.ensemble import GradientBoostingRegressor

GBR = GradientBoostingRegressor()

param_grid = {'learning_rate': [0.01,0.02,0.03,0.04],
                  'subsample'    : [0.9, 0.5, 0.2, 0.1],
                  'n_estimators' : [100,500,1000, 1500],
                  'max_depth'    : [4,6,8,10]
                 }

grid_GBR = GridSearchCV(estimator=GBR, param_grid = param_grid, cv = 2, n_jobs=-1)
grid_GBR.fit(X_train, y_train)

print(" Results from Grid Search " )
print("\n The best estimator across ALL searched params:\n",grid_GBR.best_estimator_)
print("\n The best score across ALL searched params:\n",grid_GBR.best_score_)
print("\n The best parameters across ALL searched params:\n",grid_GBR.best_params_)

 Results from Grid Search

 The best estimator across ALL searched params:
 GradientBoostingRegressor(learning_rate=0.04, max_depth=8, n_estimators=1500,
                          subsample=0.9)

 The best score across ALL searched params:
 0.9749017238306279

 The best parameters across ALL searched params:
 {'learning_rate': 0.04, 'max_depth': 8, 'n_estimators': 1500, 'subsample': 0.9}

In [16]:
gbr = GradientBoostingRegressor(learning_rate= 0.04, max_depth= 8, n_estimators= 1500, subsample= 0.9)
gbr = gbr.fit(X_train, y_train)

print('Train MSE is: ', mean_squared_error(gbr.predict(X_train), y_train))
print('Test MSE is: ', mean_squared_error(gbr.predict(X_test), y_test))
print()
print('Train RMSE is: ',  math.sqrt(mean_squared_error(gbr.predict(X_train), y_train)))
print('Test RMSE is: ', math.sqrt(mean_squared_error(gbr.predict(X_test), y_test)))
print()
print('Train MAE is: ', mean_absolute_error(gbr.predict(X_train), y_train))
print('Test MAE is: ', mean_absolute_error(gbr.predict(X_test), y_test))
print()
print('Train R2 is: ', r2_score(gbr.predict(X_train), y_train))
print('Test R2 is: ', r2_score(gbr.predict(X_test), y_test))

Train MSE is:  3857.2668986809076
Test MSE is:  160037.05054998022

Train RMSE is:  62.10689896203889
Test RMSE is:  400.0463105066465

Train MAE is:  45.05993768646041
Test MAE is:  189.97315879533045

Train R2 is:  0.9999167569609541
Test R2 is:  0.9964613325270291

In [ ]:
def diagnostic_plots(df, variable):
    # function takes a dataframe (df) and
    # the variable of interest as arguments

    # define figure size
    plt.figure(figsize=(16, 4))

    # histogram
    plt.subplot(1, 3, 1)
    sns.histplot(df[variable], bins=30, kde = True)
    plt.title('Histogram')

    # Q-Q plot
    plt.subplot(1, 3, 2)
    stats.probplot(df[variable], dist="norm", plot=plt)
    plt.ylabel('RM quantiles')

    # boxplot
    plt.subplot(1, 3, 3)
    sns.boxplot(y=df[variable])
    plt.title('Boxplot')

In [130]:
ab=AdaBoostRegressor(n_estimators=20,learning_rate=1)
ab.fit(X_train,y_train)
train_mse = mean_squared_error(ab.predict(X_train), y_train)#training mse
print('the training mean squared error is: ', train_mse) 
train_R2 = ab.score(X_train, y_train) #training r2
print('training R^2 value is: ', train_R2)

test_mse = mean_squared_error(ab.predict(X_test), y_test) #testing mse
print('the testing mean squared error is: ',test_mse)
test_R2 = ab.score(X_test, y_test) #testing r2
print('testing R^2 value is: ', test_R2)

the training mean squared error is:  8991744.007605808
training R^2 value is:  0.8063579674313232
the testing mean squared error is:  8906276.683779892
testing R^2 value is:  0.8056561654192178

In [132]:
from sklearn.model_selection import GridSearchCV
ab=AdaBoostRegressor(n_estimators=20,learning_rate=1)
param_grid = {"n_estimators":[10,50,100,300], "loss" : ['linear', 'square','exponential'], "learning_rate" : [0.5,1,2,3]}
gs = GridSearchCV(ab, param_grid=param_grid, scoring='accuracy', cv= 10, n_jobs=-1)
# cv: number of partitions for cross validation
# n_jobs: number of jobs to run in parallel, -1 means using all processors

gs = gs.fit(X_train, y_train) # 

print(gs.best_score_)
print(gs.best_params_)

c:\Users\kohja\.conda\envs\snowpark_0110\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan]
  warnings.warn(

nan
{'learning_rate': 0.5, 'loss': 'linear', 'n_estimators': 10}