In [1]:
from snowflake.snowpark.session import Session
import snowflake.snowpark.functions as F
import snowflake.snowpark.types as T
from snowflake.snowpark.window import Window
from sklearn import preprocessing # https://github.com/Snowflake-Labs/snowpark-python-demos/tree/main/sp4py_utilities
from snowflake.snowpark.functions import col

import getpass
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#nj07294.ap-southeast-1

In [3]:
accountname = 'nj07294.ap-southeast-1'
#accountname = getpass.getpass() # ORGNAME-ACCOUNTNAME (separated by minus sign)

In [4]:
username = getpass.getpass()    # SNOWFLAKE-USERNAME

········

In [9]:
password = getpass.getpass()    # SNOWFLAKE-PASSWORD

········

In [10]:
connection_parameters = {
    "account": accountname,
    "user": username,
    "password": password,
    "role": "ACCOUNTADMIN",
    "database": "FROSTBYTE_TASTY_BYTES",

    "warehouse": "HOL_WH"
}

session = Session.builder.configs(connection_parameters).create()

# Filter

In [7]:
sdf = session.table('ANALYTICS.ORDERS_V')
df=sdf.filter(col("COUNTRY")=='United States')

In [8]:
df=sdf.filter(col("COUNTRY")=='United States')

In [9]:
df.show()

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"DATE"      |"ORDER_ID"  |"TRUCK_ID"  |"ORDER_TS"           |"ORDER_DETAIL_ID"  |"LINE_NUMBER"  |"TRUCK_BRAND_NAME"  |"MENU_TYPE"  |"PRIMARY_CITY"  |"REGION"  |"COUNTRY"      |"FRANCHISE_FLAG"  |"FRANCHISE_ID"  |"FRANCHISEE_FIRST_NAME"  |"FRANCHISEE_LAST_NAME"  |"LOCATION_ID"  |"CUSTOMER_ID"  |"FIRST_NAME"  |"LAST_NAME"  |"E_MAIL"  |"PHONE_NUMBER"  |"CHILDREN_COUNT"  |"GENDER"  |"MARITAL_STATUS"  |"MENU_ITEM_ID"  |"MENU_ITEM_NAME"       |"QUANTITY"  |"UNIT_PRICE"  |"PRICE"  |"ORDER_AMOUNT"  |"ORDER_TAX_AMOUNT"  |"ORDER_DISCOUNT_AMOUNT"  |"ORDER_TOTAL"  |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2021-09-10  |440500511   |68          |2021-09-10 11:52:43  |852794007          |1              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |83              |Crepe Suzette          |1           |9.0000        |9.0000   |27.0000         |NULL                |NULL                     |27.0000        |
|2021-09-10  |440500511   |68          |2021-09-10 11:52:43  |852794006          |0              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |82              |Chicken Pot Pie Crepe  |1           |15.0000       |15.0000  |27.0000         |NULL                |NULL                     |27.0000        |
|2021-09-10  |440500511   |68          |2021-09-10 11:52:43  |852794008          |2              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |85              |Bottled Soda           |1           |3.0000        |3.0000   |27.0000         |NULL                |NULL                     |27.0000        |
|2021-09-10  |440500527   |68          |2021-09-10 11:57:27  |852794053          |0              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |82              |Chicken Pot Pie Crepe  |1           |15.0000       |15.0000  |24.0000         |NULL                |NULL                     |24.0000        |
|2021-09-10  |440500527   |68          |2021-09-10 11:57:27  |852794054          |1              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |83              |Crepe Suzette          |1           |9.0000        |9.0000   |24.0000         |NULL                |NULL                     |24.0000        |
|2021-09-10  |440500620   |68          |2021-09-10 12:43:52  |852794284          |3              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |84              |Bottled Water          |1           |2.0000        |2.0000   |83.0000         |NULL                |NULL                     |83.0000        |
|2021-09-10  |440500620   |68          |2021-09-10 12:43:52  |852794281          |0              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |81              |Breakfast Crepe        |1           |12.0000       |12.0000  |83.0000         |NULL                |NULL                     |83.0000        |
|2021-09-10  |440500620   |68          |2021-09-10 12:43:52  |852794283          |2              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |83              |Crepe Suzette          |2           |9.0000        |18.0000  |83.0000         |NULL                |NULL                     |83.0000        |
|2021-09-10  |440500620   |68          |2021-09-10 12:43:52  |852794285          |4              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |85              |Bottled Soda           |1           |3.0000        |3.0000   |83.0000         |NULL                |NULL                     |83.0000        |
|2021-09-10  |440500620   |68          |2021-09-10 12:43:52  |852794282          |1              |Le Coin des Crêpes  |Crepes       |New York City   |New York  |United States  |1                 |54              |Madeline                 |Turner                  |3161           |NULL           |NULL          |NULL         |NULL      |NULL            |NULL              |NULL      |NULL              |82              |Chicken Pot Pie Crepe  |3           |15.0000       |45.0000  |83.0000         |NULL                |NULL                     |83.0000        |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### Extracting weather data

In [10]:
connection_parameters = {
    "account": accountname,
    "user": username,
    "password": password,
    "role": "ACCOUNTADMIN",
    "database": "GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI",

    "warehouse": "HOL_WH"
}

wea_session = Session.builder.configs(connection_parameters).create()
wdf = wea_session.table('STANDARD_TILE.HISTORY_DAY')

In [11]:
wdf.show()

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"POSTAL_CODE"  |"COUNTRY"  |"DATE_VALID_STD"  |"DOY_STD"  |"MIN_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_AIR_2M_F"  |"MAX_TEMPERATURE_AIR_2M_F"  |"MIN_TEMPERATURE_WETBULB_2M_F"  |"AVG_TEMPERATURE_WETBULB_2M_F"  |"MAX_TEMPERATURE_WETBULB_2M_F"  |"MIN_TEMPERATURE_DEWPOINT_2M_F"  |"AVG_TEMPERATURE_DEWPOINT_2M_F"  |"MAX_TEMPERATURE_DEWPOINT_2M_F"  |"MIN_TEMPERATURE_FEELSLIKE_2M_F"  |"AVG_TEMPERATURE_FEELSLIKE_2M_F"  |"MAX_TEMPERATURE_FEELSLIKE_2M_F"  |"MIN_TEMPERATURE_WINDCHILL_2M_F"  |"AVG_TEMPERATURE_WINDCHILL_2M_F"  |"MAX_TEMPERATURE_WINDCHILL_2M_F"  |"MIN_TEMPERATURE_HEATINDEX_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"MAX_TEMPERATURE_HEATINDEX_2M_F"  |"MIN_HUMIDITY_RELATIVE_2M_PCT"  |"AVG_HUMIDITY_RELATIVE_2M_PCT"  |"MAX_HUMIDITY_RELATIVE_2M_PCT"  |"MIN_HUMIDITY_SPECIFIC_2M_GPKG"  |"AVG_HUMIDITY_SPECIFIC_2M_GPKG"  |"MAX_HUMIDITY_SPECIFIC_2M_GPKG"  |"MIN_PRESSURE_2M_MB"  |"AVG_PRESSURE_2M_MB"  |"MAX_PRESSURE_2M_MB"  |"MIN_PRESSURE_TENDENCY_2M_MB"  |"AVG_PRESSURE_TENDENCY_2M_MB"  |"MAX_PRESSURE_TENDENCY_2M_MB"  |"MIN_PRESSURE_MEAN_SEA_LEVEL_MB"  |"AVG_PRESSURE_MEAN_SEA_LEVEL_MB"  |"MAX_PRESSURE_MEAN_SEA_LEVEL_MB"  |"MIN_WIND_SPEED_10M_MPH"  |"AVG_WIND_SPEED_10M_MPH"  |"MAX_WIND_SPEED_10M_MPH"  |"AVG_WIND_DIRECTION_10M_DEG"  |"MIN_WIND_SPEED_80M_MPH"  |"AVG_WIND_SPEED_80M_MPH"  |"MAX_WIND_SPEED_80M_MPH"  |"AVG_WIND_DIRECTION_80M_DEG"  |"MIN_WIND_SPEED_100M_MPH"  |"AVG_WIND_SPEED_100M_MPH"  |"MAX_WIND_SPEED_100M_MPH"  |"AVG_WIND_DIRECTION_100M_DEG"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"MIN_CLOUD_COVER_TOT_PCT"  |"AVG_CLOUD_COVER_TOT_PCT"  |"MAX_CLOUD_COVER_TOT_PCT"  |"MIN_RADIATION_SOLAR_TOTAL_WPM2"  |"AVG_RADIATION_SOLAR_TOTAL_WPM2"  |"MAX_RADIATION_SOLAR_TOTAL_WPM2"  |"TOT_RADIATION_SOLAR_TOTAL_WPM2"  |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|102103         |NG         |2021-07-01        |182        |75.2                        |80.2                        |87.7                        |73.7                            |74.6                            |76.2                            |70.1                             |72.2                             |73.5                             |79.5                              |85.2                              |93.8                              |75.2                              |80.2                              |87.7                              |79.5                              |85.2                              |93.8                              |56                              |78                              |93                              |16.0                             |17.0                             |17.7                             |1006.30               |1008.00               |1009.58               |-1.1                           |-0.1                           |0.7                            |1011.70                           |1013.50                           |1015.10                           |3.2                       |5.7                       |8.4                       |214                           |5.2                       |9.6                       |12.1                      |218                           |5.5                        |10.0                       |12.8                       |218                            |0.25                    |0.00               |0.0                 |66                         |91                         |100                        |0.0                               |258.9                             |921.4                             |6214.7                            |
|110054         |IN         |2021-07-01        |182        |91.1                        |101.5                       |113.3                       |68.6                            |74.2                            |78.5                            |45.9                             |56.7                             |64.4                             |91.2                              |103.1                             |114.7                             |91.1                              |101.5                             |113.3                             |91.2                              |103.1                             |114.7                             |16                              |23                              |32                              |7.1                              |10.9                             |14.0                             |967.78                |970.59                |972.14                |-1.2                           |0.0                            |1.1                            |989.80                            |992.70                            |994.40                            |2.4                       |6.9                       |9.5                       |251                           |2.8                       |9.3                       |12.7                      |254                           |3.0                        |10.0                       |14.1                       |255                            |0.00                    |0.00               |0.0                 |13                         |74                         |100                        |0.0                               |312.9                             |976.8                             |7510.7                            |
|2044           |AU         |2021-07-01        |182        |49.3                        |55.6                        |60.7                        |48.7                            |54.2                            |57.3                            |48.3                             |53.2                             |55.9                             |49.1                              |55.5                              |60.7                              |49.1                              |55.5                              |60.7                              |49.3                              |55.6                              |60.7                              |81                              |92                              |98                              |7.1                              |8.5                              |9.4                              |1016.14               |1019.52               |1022.80               |-1.3                           |-0.3                           |0.3                            |1019.20                           |1022.80                           |1026.10                           |1.5                       |3.2                       |5.2                       |332                           |2.1                       |4.8                       |8.1                       |342                           |2.3                        |5.2                        |8.8                        |344                            |0.13                    |0.00               |0.0                 |5                          |85                         |100                        |0.0                               |83.3                              |344.3                             |1997.7                            |
|21745-690      |BR         |2021-07-01        |182        |54.7                        |60.0                        |69.3                        |52.4                            |56.1                            |62.6                            |49.0                             |53.3                             |58.9                             |54.3                              |59.7                              |69.3                              |54.3                              |59.7                              |69.3                              |54.7                              |60.0                              |69.3                              |62                              |79                              |96                              |7.3                              |8.6                              |10.5                             |1013.54               |1014.97               |1017.00               |-1.2                           |0.0                            |0.8                            |1024.50                           |1026.20                           |1028.00                           |2.7                       |5.2                       |7.3                       |276                           |4.4                       |7.8                       |11.6                      |264                           |4.7                        |8.4                        |12.8                       |263                            |0.00                    |0.00               |0.0                 |0                          |29                         |80                         |0.0                               |146.5                             |647.4                             |3515.9                            |
|60596          |DE         |2021-07-01        |182        |54.9                        |57.7                        |60.8                        |54.1                            |56.0                            |58.5                            |53.5                             |54.8                             |57.4                             |53.5                              |56.7                              |60.1                              |53.5                              |56.7                              |60.1                              |54.9                              |57.7                              |60.8                              |81                              |90                              |99                              |8.7                              |9.2                              |10.1                             |994.27                |996.34                |998.28                |-0.5                           |0.1                            |0.6                            |1013.70                           |1015.80                           |1017.50                           |2.0                       |6.6                       |9.4                       |267                           |3.6                       |9.8                       |13.0                      |271                           |4.1                        |10.8                       |14.3                       |272                            |0.10                    |0.00               |0.0                 |65                         |95                         |100                        |0.0                               |85.6                              |293.8                             |2055.0                            |
|SE1 7GP        |GB         |2021-07-01        |182        |51.5                        |60.1                        |68.8                        |50.7                            |56.1                            |62.1                            |49.9                             |53.3                             |59.6                             |51.5                              |60.1                              |68.8                              |51.5                              |60.1                              |68.8                              |51.5                              |60.1                              |68.8                              |60                              |79                              |94                              |7.6                              |8.7                              |10.9                             |1009.51               |1010.45               |1011.27               |-0.4                           |-0.1                           |0.2                            |1017.00                           |1017.80                           |1018.40                           |0.7                       |3.1                       |5.9                       |351                           |1.3                       |4.3                       |7.0                       |354                           |1.4                        |4.4                        |7.1                        |353                            |0.00                    |0.00               |0.0                 |15                         |79                         |100                        |0.0                               |261.6                             |747.8                             |6277.9                            |
|WD25 7LR       |GB         |2021-07-01        |182        |50.6                        |59.7                        |67.7                        |49.8                            |55.8                            |61.7                            |49.0                             |53.1                             |59.5                             |50.6                              |59.6                              |67.7                              |50.6                              |59.6                              |67.7                              |50.6                              |59.7                              |67.7                              |61                              |80                              |95                              |7.3                              |8.6                              |10.8                             |1007.47               |1008.43               |1009.34               |-0.4                           |-0.1                           |0.3                            |1016.90                           |1017.80                           |1018.40                           |1.0                       |3.0                       |5.5                       |357                           |1.6                       |4.1                       |6.7                       |3                             |1.7                        |4.2                        |6.8                        |2                              |0.00                    |0.00               |0.0                 |18                         |80                         |100                        |0.0                               |266.6                             |680.0                             |6398.7                            |
|01059          |US         |2021-07-01        |182        |66.9                        |71.5                        |76.7                        |66.3                            |69.9                            |72.0                            |66.0                             |69.2                             |70.7                             |66.9                              |71.9                              |80.2                              |66.9                              |71.5                              |76.7                              |66.9                              |71.9                              |80.2                              |78                              |93                              |100                             |13.7                             |15.3                             |16.1                             |999.18                |1001.74               |1003.29               |-0.9                           |-0.2                           |0.5                            |1007.40                           |1010.40                           |1012.10                           |0.0                       |3.0                       |5.5                       |239                           |0.6                       |5.5                       |10.3                      |218                           |2.0                        |4.9                        |8.8                        |261                            |0.88                    |0.00               |0.0                 |74                         |98                         |100                        |0.0                               |159.3                             |773.9                             |3822.7                            |

In [12]:
wdf2 = wdf.to_pandas()

In [13]:
wdf2.head()

,POSTAL_CODE,COUNTRY,DATE_VALID_STD,DOY_STD,MIN_TEMPERATURE_AIR_2M_F,AVG_TEMPERATURE_AIR_2M_F,MAX_TEMPERATURE_AIR_2M_F,MIN_TEMPERATURE_WETBULB_2M_F,AVG_TEMPERATURE_WETBULB_2M_F,MAX_TEMPERATURE_WETBULB_2M_F,...,TOT_PRECIPITATION_IN,TOT_SNOWFALL_IN,TOT_SNOWDEPTH_IN,MIN_CLOUD_COVER_TOT_PCT,AVG_CLOUD_COVER_TOT_PCT,MAX_CLOUD_COVER_TOT_PCT,MIN_RADIATION_SOLAR_TOTAL_WPM2,AVG_RADIATION_SOLAR_TOTAL_WPM2,MAX_RADIATION_SOLAR_TOTAL_WPM2,TOT_RADIATION_SOLAR_TOTAL_WPM2
0,102103,NG,2021-11-16,320,77.5,81.9,89.6,75.6,77.0,78.6,...,0.07,0.0,0.0,83,96,100,0.0,236.9,857.0,5686.0
1,110054,IN,2021-11-16,320,50.7,62.7,77.1,43.8,51.9,60.0,...,0.00,0.0,0.0,0,1,6,0.0,189.7,713.2,4552.6
2,2044,AU,2021-11-16,320,52.6,59.2,66.0,49.1,51.4,54.3,...,0.00,0.0,0.0,1,15,86,0.0,371.1,1084.2,8905.7
3,21745-690,BR,2021-11-16,320,63.7,74.8,87.9,61.1,67.1,72.3,...,0.00,0.0,0.0,2,55,100,0.0,350.7,1078.2,8415.6
4,60596,DE,2021-11-16,320,40.4,42.0,43.9,39.5,40.9,42.3,...,0.00,0.0,0.0,99,100,100,0.0,12.8,59.6,306.7

### Drop columns (like discount amount, etc)

In [14]:
df=df.drop(['ORDER_DISCOUNT_AMOUNT','ORDER_TAX_AMOUNT','ORDER_AMOUNT','PRICE','UNIT_PRICE','QUANTITY','MENU_ITEM_NAME','MENU_ITEM_ID','MARITAL_STATUS','GENDER','CHILDREN_COUNT','PHONE_NUMBER','E_MAIL','LAST_NAME','FIRST_NAME','CUSTOMER_ID','FRANCHISEE_FIRST_NAME','FRANCHISEE_LAST_NAME','FRANCHISE_ID','FRANCHISE_FLAG','LINE_NUMBER','ORDER_ID'])

### Transform order_ts to year, month, day, day of the week, hour, public holiday binary

In [15]:
df=df.withColumn("Month",F.month(df["ORDER_TS"]))
df=df.withColumn("DOW",F.dayofweek(df["ORDER_TS"]))
df=df.withColumn("Day",F.dayofmonth(df["ORDER_TS"]))
df=df.withColumn("Hour",F.hour(df["ORDER_TS"]))
df=df.withColumn("WOM", ((F.dayofmonth(F.col('ORDER_TS')) - 1) / 7 + 1).cast('integer'))

In [16]:
# Create public holiday column binary
public_holidays = [
    {'Month': 7, 'Day': 4, 'DOW': None, 'WOM': None},  # 4th of July
    {'Month': 12, 'Day': 24, 'DOW': None, 'WOM': None},  # Christmas Eve
    {'Month': 12, 'Day': 25, 'DOW': None, 'WOM': None},  # Christmas Day
    {'Month': 10, 'Day': None, 'DOW': 'Monday', 'WOM': 2},  # Columbus Day (second Monday in October)
    {'Month': 6, 'Day': 19, 'DOW': None, 'WOM': None},  # Juneteenth
    {'Month': 9, 'Day': None, 'DOW': 'Monday', 'WOM': 1},  # Labor Day (first Monday in September)
    {'Month': 1, 'Day': None, 'DOW': 'Monday', 'WOM': 3},  # Martin Luther King, Jr. Day (third Monday in January)
    {'Month': 5, 'Day': None, 'DOW': 'Monday', 'WOM': -1},  # Memorial Day (last Monday in May)
    {'Month': 1, 'Day': 1, 'DOW': None, 'WOM': None},  # New Year's Day
    {'Month': 12, 'Day': 31, 'DOW': None, 'WOM': None},  # New Year's Eve
    {'Month': 11, 'Day': None, 'DOW': 'Thursday', 'WOM': 4},  # Thanksgiving Day (fourth Thursday in November)
    {'Month': 11, 'Day': None, 'DOW': 'Wednesday', 'WOM': 4},  # Thanksgiving Eve (fourth Wednesday in November)
    {'Month': 2, 'Day': 14, 'DOW': None, 'WOM': None},  # Valentine's Day
    {'Month': 11, 'Day': 11, 'DOW': None, 'WOM': None},  # Veterans Day
    {'Month': 10, 'Day': 31, 'DOW': None, 'WOM': None},  # Halloween
    {'Month': 3, 'Day': 17, 'DOW': None, 'WOM': None},  # St. Patrick's Day
    {'Month': 11, 'Day': 25, 'DOW': 'Friday', 'WOM': None},  # Black Friday
    {'Month': 12, 'Day': 26, 'DOW': None, 'WOM': None},  # Boxing Day
]

In [17]:
from snowflake.snowpark.functions import udf
from snowflake.snowpark.types import IntegerType
def is_public_holiday(month, day, dow, wom):
    for holiday in public_holidays:
        if holiday['Month'] == month and holiday['DOW'] == dow and holiday['WOM'] == wom:
            if holiday['Day'] is None:
                return True
            elif holiday['Day'] == day:
                return True
    return False

session.sql("USE SCHEMA RAW_POS").collect()
@udf(session=session, name='public_holiday', input_types=[IntegerType(), IntegerType(), IntegerType(), IntegerType()], return_type=IntegerType(), is_permanent=False, replace=True)
def public_holiday(month: int, day: int, dow: int, wom: int) -> int:
    if is_public_holiday(month, day, dow, wom):
        return 1
    else:
        return 0

df=df.withColumn('PUBLIC_HOLIDAY', public_holiday(F.month(F.col('DATE')), F.dayofmonth(F.col('DATE')), F.dayofweek(F.col('DATE')), ((F.col('Day') - 1) / 7 + 1).cast('integer')))

## Grouping

In [18]:
df.show()

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"DATE"      |"TRUCK_ID"  |"ORDER_TS"           |"ORDER_DETAIL_ID"  |"TRUCK_BRAND_NAME"  |"MENU_TYPE"  |"PRIMARY_CITY"  |"REGION"  |"COUNTRY"      |"LOCATION_ID"  |"ORDER_TOTAL"  |"MONTH"  |"DOW"  |"DAY"  |"HOUR"  |"WOM"  |"PUBLIC_HOLIDAY"  |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2022-05-07  |17          |2022-05-07 19:03:18  |883147691          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |63.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:03:18  |883147693          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |63.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:03:18  |883147694          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |63.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:03:18  |883147695          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |63.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:03:18  |883147692          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |63.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:25:55  |883147763          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |20.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:25:55  |883147764          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |20.0000        |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:34:30  |883147781          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |105.0000       |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:34:30  |883147782          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |105.0000       |5        |6      |7      |19      |2      |0                 |
|2022-05-07  |17          |2022-05-07 19:34:30  |883147783          |Smoky BBQ           |BBQ          |Denver          |Colorado  |United States  |5112           |105.0000       |5        |6      |7      |19      |2      |0                 |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [19]:
grouped_df = df.groupBy("DATE","TRUCK_ID","MONTH","HOUR","DOW","DAY","Menu_Type","LOCATION_ID","PUBLIC_HOLIDAY").agg(F.sum("ORDER_TOTAL"))

# Joining with weather data

In [20]:
connection_parameters = {
    "account": accountname,
    "user": username,
    "password": password,
    "role": "ACCOUNTADMIN",
    "database": "GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI",

    "warehouse": "HOL_WH"
}

wea_session = Session.builder.configs(connection_parameters).create()
wdf = wea_session.table('STANDARD_TILE.HISTORY_DAY')

In [21]:
wdf=wea_session.sql("select * From STANDARD_TILE.HISTORY_DAY")

In [22]:
print(type(wdf))
#print(type(semi_final_df))

<class 'snowflake.snowpark.dataframe.DataFrame'>

In [23]:
grouped_df.show()

---------------------------------------------------------------------------------------------------------------------------------------
|"DATE"      |"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"MENU_TYPE"     |"LOCATION_ID"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |
---------------------------------------------------------------------------------------------------------------------------------------
|2022-05-07  |18          |5        |22      |6      |7      |Tacos           |1861           |0                 |2336.5000           |
|2022-05-07  |18          |5        |18      |6      |7      |Tacos           |1861           |0                 |10424.5000          |
|2022-05-07  |20          |5        |8       |6      |7      |Ramen           |14812          |0                 |10043.2500          |
|2022-05-07  |21          |5        |10      |6      |7      |Grilled Cheese  |14792          |0                 |1462.0000           |
|2022-05-07  |21          |5        |13      |6      |7      |Grilled Cheese  |14792          |0                 |3005.0000           |
|2022-05-07  |21          |5        |20      |6      |7      |Grilled Cheese  |1043           |0                 |5120.0000           |
|2022-05-07  |23          |5        |10      |6      |7      |Crepes          |3155           |0                 |2243.0000           |
|2022-05-07  |23          |5        |17      |6      |7      |Crepes          |14875          |0                 |4356.0000           |
|2022-05-07  |25          |5        |21      |6      |7      |Hot Dogs        |5106           |0                 |5488.0000           |
|2022-05-07  |26          |5        |17      |6      |7      |Poutine         |14926          |0                 |7305.0000           |
---------------------------------------------------------------------------------------------------------------------------------------

In [24]:
wdf_re=wdf.with_column_renamed(col("DATE_VALID_STD"), "DATE")

In [25]:
sdf_loc = session.table('RAW_POS.Location_New')

In [26]:
sdf_loc_dr=sdf_loc.drop("PLACEKEY","ISO_COUNTRY_CODE")

In [27]:
sdf_loc_dr.show()

---------------------------------------------------------------------------------------------------------------------------------------------------------------
|"LOCATION_ID"  |"LOCATION"                                        |"CITY"  |"REGION"  |"COUNTRY"      |"LAT"               |"LONG"               |"ZIPCODE"  |
---------------------------------------------------------------------------------------------------------------------------------------------------------------
|1030           |University Of Colorado Museum Of Natural History  |Denver  |CO        |United States  |40.00768674326263   |-105.26970066129032  |80802      |
|1031           |Denver Technological Center                       |Denver  |CO        |United States  |39.62735682905758   |-104.91269066527825  |80237      |
|1032           |Heritage Club At Denver Tech Center               |Denver  |CO        |United States  |39.62526657316754   |-104.91238594440485  |80237      |
|1033           |Porter Wound Care Center                          |Denver  |CO        |United States  |39.671421009959225  |-104.97636575469211  |80210      |
|1034           |Emeritus at Highline                              |Denver  |CO        |United States  |39.68681241616432   |-104.89274135984651  |80247      |
|1035           |Cherry Creek Gun Club                             |Denver  |CO        |United States  |39.69212431173931   |-104.8771588467281   |80247      |
|1036           |The Courtyards at Mountain View                   |Denver  |CO        |United States  |39.69737086762524   |-104.89264470571358  |80247      |
|1037           |The Denver Hospice                                |Denver  |CO        |United States  |39.71958553918071   |-104.89179382614257  |80230      |
|1038           |Sandstone Care                                    |Denver  |CO        |United States  |39.67758633438455   |-104.93392167584601  |80222      |
|1039           |Serenity House Assisted Living Office             |Denver  |CO        |United States  |39.668469528717374  |-104.92850076530557  |80222      |
---------------------------------------------------------------------------------------------------------------------------------------------------------------

In [28]:
semi_final_df=grouped_df.join(sdf_loc_dr, grouped_df["LOCATION_ID"] == sdf_loc_dr["LOCATION_ID"])

In [29]:
semi_final_df.show()

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"DATE"      |"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"MENU_TYPE"  |"l_3epo_LOCATION_ID"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"r_fvrn_LOCATION_ID"  |"LOCATION"               |"CITY"         |"REGION"  |"COUNTRY"      |"LAT"               |"LONG"              |"ZIPCODE"  |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2022-10-31  |68          |10       |18      |1      |31     |Crepes       |3161                  |0                 |16919.0000          |3161                  |Poseidon Bakery          |New York City  |NY        |United States  |40.75958528962577   |-73.99161112180775  |10036      |
|2022-10-31  |68          |10       |21      |1      |31     |Crepes       |3161                  |0                 |16599.0000          |3161                  |Poseidon Bakery          |New York City  |NY        |United States  |40.75958528962577   |-73.99161112180775  |10036      |
|2022-10-31  |69          |10       |9       |1      |31     |Ethiopian    |1927                  |0                 |15888.0000          |1927                  |Chanin News Corporation  |New York City  |NY        |United States  |40.75161449358854   |-73.97906744647469  |10017      |
|2022-10-31  |69          |10       |11      |1      |31     |Ethiopian    |1927                  |0                 |17361.0000          |1927                  |Chanin News Corporation  |New York City  |NY        |United States  |40.75161449358854   |-73.97906744647469  |10017      |
|2022-10-31  |69          |10       |12      |1      |31     |Ethiopian    |1927                  |0                 |14016.0000          |1927                  |Chanin News Corporation  |New York City  |NY        |United States  |40.75161449358854   |-73.97906744647469  |10017      |
|2022-10-31  |69          |10       |16      |1      |31     |Ethiopian    |15219                 |0                 |17560.0000          |15219                 |Machate Circle           |New York City  |NY        |United States  |40.650644678706875  |-73.97207955535434  |11218      |
|2022-10-31  |70          |10       |21      |1      |31     |Hot Dogs     |15141                 |0                 |11782.0000          |15141                 |Haven Avenue             |New York City  |NY        |United States  |40.848571237679955  |-73.94302955337622  |10033      |
|2022-10-31  |71          |10       |11      |1      |31     |Poutine      |14116                 |0                 |18408.0000          |14116                 |Chelsea Eats             |New York City  |NY        |United States  |40.72273049401267   |-73.98588479015281  |10009      |
|2022-10-31  |72          |10       |15      |1      |31     |Gyros        |4203                  |0                 |18011.0000          |4203                  |Sugarfina                |New York City  |NY        |United States  |40.71147428309848   |-74.01110585734753  |10006      |
|2022-10-31  |72          |10       |17      |1      |31     |Gyros        |4203                  |0                 |18028.0000          |4203                  |Sugarfina                |New York City  |NY        |United States  |40.71147428309848   |-74.01110585734753  |10006      |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [30]:
# # # # weather=wdf_re.to_pandas()
# weather=wdf_re.to_pandas()
# syntax=pd.io.sql.get_schema(weather, "weather_data")
# session.use_schema("ANALYTICS")
# session.sql(
    
#     syntax
# ).collect()
# session.write_pandas(
#     df=weather,
#     table_name="weather_data",
#     database="frostbyte_tasty_bytes",
#     schema="ANALYTICS",
#     quote_identifiers=False,
#     overwrite=True)

In [31]:
semi_final_df=semi_final_df.with_column_renamed(col("ZIPCODE"), "POSTAL_CODE")

In [32]:
type(wdf_re["DATE"])

snowflake.snowpark.column.Column

In [33]:
wdf = session.table('RAW_POS.weather_data')
wdf=wdf.select("POSTAL_CODE","DATE","COUNTRY","AVG_TEMPERATURE_AIR_2M_F","AVG_TEMPERATURE_HEATINDEX_2M_F","TOT_PRECIPITATION_IN","TOT_SNOWFALL_IN","TOT_SNOWDEPTH_IN","AVG_CLOUD_COVER_TOT_PCT")

In [34]:
final_df = semi_final_df.join(wdf, (semi_final_df["DATE"] == wdf["DATE"]) & (semi_final_df["POSTAL_CODE"] == wdf["POSTAL_CODE"])  )

In [35]:
session.use_schema("ANALYTICS")
final_df.write.save_as_table(table_name="sales_prediction", mode='overwrite')

Failed to execute query [queryID: 01ac528f-3200-bc30-0003-d8760006b0be]  CREATE  OR  REPLACE    TABLE  sales_prediction AS  SELECT  *  FROM ( SELECT  *  FROM (( SELECT "DATE" AS "l_lsl4_DATE", "TRUCK_ID" AS "TRUCK_ID", "MONTH" AS "MONTH", "HOUR" AS "HOUR", "DOW" AS "DOW", "DAY" AS "DAY", "MENU_TYPE" AS "MENU_TYPE", "l_3epo_LOCATION_ID" AS "l_3epo_LOCATION_ID", "PUBLIC_HOLIDAY" AS "PUBLIC_HOLIDAY", "SUM(ORDER_TOTAL)" AS "SUM(ORDER_TOTAL)", "r_fvrn_LOCATION_ID" AS "r_fvrn_LOCATION_ID", "LOCATION" AS "LOCATION", "CITY" AS "CITY", "REGION" AS "REGION", "COUNTRY" AS "l_lsl4_COUNTRY", "LAT" AS "LAT", "LONG" AS "LONG", "POSTAL_CODE" AS "l_lsl4_POSTAL_CODE" FROM ( SELECT "DATE", "TRUCK_ID", "MONTH", "HOUR", "DOW", "DAY", "MENU_TYPE", "l_3epo_LOCATION_ID", "PUBLIC_HOLIDAY", "SUM(ORDER_TOTAL)", "r_fvrn_LOCATION_ID", "LOCATION", "CITY", "REGION", "COUNTRY", "LAT", "LONG", "ZIPCODE" AS "POSTAL_CODE" FROM ( SELECT  *  FROM (( SELECT "DATE" AS "DATE", "TRUCK_ID" AS "TRUCK_ID", "MONTH" AS "MONTH", "HOUR" AS "HOUR", "DOW" AS "DOW", "DAY" AS "DAY", "MENU_TYPE" AS "MENU_TYPE", "LOCATION_ID" AS "l_3epo_LOCATION_ID", "PUBLIC_HOLIDAY" AS "PUBLIC_HOLIDAY", "SUM(ORDER_TOTAL)" AS "SUM(ORDER_TOTAL)" FROM ( SELECT "DATE", "TRUCK_ID", "MONTH", "HOUR", "DOW", "DAY", "MENU_TYPE", "LOCATION_ID", "PUBLIC_HOLIDAY", sum("ORDER_TOTAL") AS "SUM(ORDER_TOTAL)" FROM ( SELECT "DATE", "TRUCK_ID", "ORDER_TS", "ORDER_DETAIL_ID", "TRUCK_BRAND_NAME", "MENU_TYPE", "PRIMARY_CITY", "REGION", "COUNTRY", "LOCATION_ID", "ORDER_TOTAL", "MONTH", "DOW", "DAY", "HOUR", "WOM", public_holiday(month("DATE"), dayofmonth("DATE"), dayofweek("DATE"),  CAST (((("DAY" - 1 :: INT) / 7 :: INT) + 1 :: INT) AS INT)) AS "PUBLIC_HOLIDAY" FROM ( SELECT "DATE", "TRUCK_ID", "ORDER_TS", "ORDER_DETAIL_ID", "TRUCK_BRAND_NAME", "MENU_TYPE", "PRIMARY_CITY", "REGION", "COUNTRY", "LOCATION_ID", "ORDER_TOTAL", "MONTH", "DOW", "DAY", "HOUR",  CAST ((((dayofmonth("ORDER_TS") - 1 :: INT) / 7 :: INT) + 1 :: INT) AS INT) AS "WOM" FROM ( SELECT "DATE", "TRUCK_ID", "ORDER_TS", "ORDER_DETAIL_ID", "TRUCK_BRAND_NAME", "MENU_TYPE", "PRIMARY_CITY", "REGION", "COUNTRY", "LOCATION_ID", "ORDER_TOTAL", "MONTH", "DOW", "DAY", hour("ORDER_TS") AS "HOUR" FROM ( SELECT "DATE", "TRUCK_ID", "ORDER_TS", "ORDER_DETAIL_ID", "TRUCK_BRAND_NAME", "MENU_TYPE", "PRIMARY_CITY", "REGION", "COUNTRY", "LOCATION_ID", "ORDER_TOTAL", "MONTH", "DOW", dayofmonth("ORDER_TS") AS "DAY" FROM ( SELECT "DATE", "TRUCK_ID", "ORDER_TS", "ORDER_DETAIL_ID", "TRUCK_BRAND_NAME", "MENU_TYPE", "PRIMARY_CITY", "REGION", "COUNTRY", "LOCATION_ID", "ORDER_TOTAL", "MONTH", dayofweek("ORDER_TS") AS "DOW" FROM ( SELECT "DATE", "TRUCK_ID", "ORDER_TS", "ORDER_DETAIL_ID", "TRUCK_BRAND_NAME", "MENU_TYPE", "PRIMARY_CITY", "REGION", "COUNTRY", "LOCATION_ID", "ORDER_TOTAL", month("ORDER_TS") AS "MONTH" FROM ( SELECT "DATE", "TRUCK_ID", "ORDER_TS", "ORDER_DETAIL_ID", "TRUCK_BRAND_NAME", "MENU_TYPE", "PRIMARY_CITY", "REGION", "COUNTRY", "LOCATION_ID", "ORDER_TOTAL" FROM ( SELECT  *  FROM ( SELECT  *  FROM (ANALYTICS.ORDERS_V)) WHERE ("COUNTRY" = 'United States'))))))))) GROUP BY "DATE", "TRUCK_ID", "MONTH", "HOUR", "DOW", "DAY", "MENU_TYPE", "LOCATION_ID", "PUBLIC_HOLIDAY")) AS SNOWPARK_TEMP_TABLE_YVR0PVJXMQ INNER JOIN ( SELECT "LOCATION_ID" AS "r_fvrn_LOCATION_ID", "LOCATION" AS "LOCATION", "CITY" AS "CITY", "REGION" AS "REGION", "COUNTRY" AS "COUNTRY", "LAT" AS "LAT", "LONG" AS "LONG", "ZIPCODE" AS "ZIPCODE" FROM ( SELECT "LOCATION_ID", "LOCATION", "CITY", "REGION", "COUNTRY", "LAT", "LONG", "ZIPCODE" FROM ( SELECT  *  FROM (RAW_POS.Location_New)))) AS SNOWPARK_TEMP_TABLE_Q8IXPFP0MG ON ("l_3epo_LOCATION_ID" = "r_fvrn_LOCATION_ID"))))) AS SNOWPARK_TEMP_TABLE_30EP4ULOSG INNER JOIN ( SELECT "POSTAL_CODE" AS "r_t82j_POSTAL_CODE", "DATE" AS "r_t82j_DATE", "COUNTRY" AS "r_t82j_COUNTRY", "AVG_TEMPERATURE_AIR_2M_F" AS "AVG_TEMPERATURE_AIR_2M_F", "AVG_TEMPERATURE_HEATINDEX_2M_F" AS "AVG_TEMPERATURE_HEATINDEX_2M_F", "TOT_PRECIPITATION_IN" AS "TOT_PRECIPITATION_IN", "TOT_SNOWFALL_IN" AS "TOT_SNOWFALL_IN", "TOT_SNOWDEPTH_IN" AS "TOT_SNOWDEPTH_IN", "AVG_CLOUD_COVER_TOT_PCT" AS "AVG_CLOUD_COVER_TOT_PCT" FROM ( SELECT "POSTAL_CODE", "DATE", "COUNTRY", "AVG_TEMPERATURE_AIR_2M_F", "AVG_TEMPERATURE_HEATINDEX_2M_F", "TOT_PRECIPITATION_IN", "TOT_SNOWFALL_IN", "TOT_SNOWDEPTH_IN", "AVG_CLOUD_COVER_TOT_PCT" FROM ( SELECT  *  FROM (RAW_POS.weather_data)))) AS SNOWPARK_TEMP_TABLE_1U15BZ1OKM ON (("l_lsl4_DATE" = "r_t82j_DATE") AND ("l_lsl4_POSTAL_CODE" = "r_t82j_POSTAL_CODE"))))
002140 (42601): SQL compilation error:
Unknown function PUBLIC_HOLIDAY

SnowparkSQLException: (1304): 002140 (42601): SQL compilation error:
Unknown function PUBLIC_HOLIDAY

## Encoding

In [65]:
to_encode_df = session.table('ANALYTICS.SALES_PREDICTION')

In [66]:
to_encode_df.show()

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"l_08qh_DATE"  |"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"MENU_TYPE"   |"l_jho6_LOCATION_ID"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"r_sim4_LOCATION_ID"  |"LOCATION"       |"CITY"   |"REGION"  |"l_08qh_COUNTRY"  |"LAT"              |"LONG"               |"l_08qh_POSTAL_CODE"  |"r_c08p_POSTAL_CODE"  |"r_c08p_DATE"  |"r_c08p_COUNTRY"  |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2021-10-25     |32          |10       |16      |1      |25     |BBQ           |5176                  |0                 |1513.0000           |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |18      |1      |25     |BBQ           |5176                  |0                 |3337.0000           |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |21      |1      |25     |BBQ           |5176                  |0                 |5933.0000           |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |22      |1      |25     |BBQ           |5176                  |0                 |99.0000             |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |15      |1      |25     |BBQ           |5176                  |0                 |819.0000            |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |17      |1      |25     |BBQ           |5176                  |0                 |3012.0000           |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |19      |1      |25     |BBQ           |5176                  |0                 |7724.0000           |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-10-25     |32          |10       |20      |1      |25     |BBQ           |5176                  |0                 |7843.0000           |5176                  |York Playground  |Seattle  |WA        |United States     |47.57341023266439  |-122.37588016173208  |98126                 |98126                 |2021-10-25     |US                |53.2                        |53.2                              |0.26                    |0.0                |0.0                 |84                         |
|2021-12-08     |19          |12       |8       |3      |8      |Mac & Cheese  |14950                 |0                 |1362.0000           |14950                 |Speer Blvd Park  |Denver   |CO        |United States     |39.75062334730824  |-105.00517561043424  |80217                 |80217                 |2021-12-08     |US                |44.2                        |44.2                              |0.0                     |0.0                |0.0                 |61                         |
|2021-12-08     |19          |12       |12      |3      |8      |Mac & Cheese  |14950                 |0                 |5976.0000           |14950                 |Speer Blvd Park  |Denver   |CO        |United States     |39.75062334730824  |-105.00517561043424  |80217                 |80217                 |2021-12-08     |US                |44.2                        |44.2                              |0.0                     |0.0                |0.0                 |61                         |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [72]:
columns_to_drop = ['"r_sim4_LOCATION_ID"','"l_08qh_COUNTRY"','"l_08qh_POSTAL_CODE"','"r_c08p_DATE"','"r_c08p_COUNTRY"']
new_columns  = [c for c in to_encode_df.columns if c not in columns_to_drop]
dropped_df = to_encode_df.select(*new_columns)

In [91]:
connection_parameters = {
    "account": accountname,
    "user": username,
    "password": password,
    "role": "ACCOUNTADMIN",
    "database": "FROSTBYTE_TASTY_BYTE",

    "warehouse": "HOL_WH"
}

nt_session = Session.builder.configs(connection_parameters).create()
sales = nt_session.sql("Select * from ANALYTICS.DEMAND_FORECAST_TRAINING_Base")

In [92]:
sales.show()

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"DATE"      |"SHIFT"  |"PRIMARY_CITY"  |"LOCATION_ID"  |"MENU_TYPE"   |"MENU_ITEM_ID"  |"MONTH_OF_YEAR"  |"DAY_OF_WEEK"  |"UNIT_PRICE"  |"PREV_YEAR_MONTH_SALES_CITY"  |"PREV_YEAR_MONTH_SALES_LOCATION"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_ITEM"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |"DAY_OF_WEEK_AVG_CITY"  |"DAY_OF_WEEK_AVG_LOCATION"  |"DAY_OF_WEEK_AVG_CITY_MENU_ITEM"  |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"QUANTITY"  |"AVG_SALES_7D_LOCATION"  |"AVG_SALES_14D_LOCATION"  |"AVG_SALES_28D_LOCATION"  |"AVG_SALES_LOCATION"  |"AVG_SALES_7D_LOCATION_MENU_TYPE"  |"AVG_SALES_14D_LOCATION_MENU_TYPE"  |"AVG_SALES_28D_LOCATION_MENU_TYPE"  |"AVG_SALES_LOCATION_MENU_TYPE"  |"AVG_QUANTITY_7D_LOCATION_MENU_ITEM"  |"AVG_QUANTITY_14D_LOCATION_MENU_ITEM"  |"AVG_QUANTITY_28D_LOCATION_MENU_ITEM"  |"AVG_QUANTITY_LOCATION_MENU_ITEM"  |"AVG_SALES_7D_CITY"  |"AVG_SALES_14D_CITY"  |"AVG_SALES_28D_CITY"  |"AVG_SALES_CITY"  |"AVG_SALES_7D_CITY_MENU_TYPE"  |"AVG_SALES_14D_CITY_MENU_TYPE"  |"AVG_SALES_28D_CITY_MENU_TYPE"  |"AVG_SALES_CITY_MENU_TYPE"  |"AVG_QUANTITY_7D_CITY_MENU_ITEM"  |"AVG_QUANTITY_14D_CITY_MENU_ITEM"  |"AVG_QUANTITY_28D_CITY_MENU_ITEM"  |"AVG_QUANTITY_CITY_MENU_ITEM"  |"AVG_SALES_7D_MENU_TYPE"  |"AVG_SALES_14D_MENU_TYPE"  |"AVG_SALES_28D_MENU_TYPE"  |"AVG_SALES_MENU_TYPE"  |"AVG_QUANTITY_7D_MENU_ITEM"  |"AVG_QUANTITY_14D_MENU_ITEM"  |"AVG_QUANTITY_28D_MENU_ITEM"  |"AVG_QUANTITY_MENU_ITEM"  |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2021-11-14  |PM       |Cairo           |10565          |Ice Cream     |16              |11               |0              |3.0000        |1852815.00                    |12634.00                          |NULL                                    |NULL                                    |2307.47021              |723.16666                   |211.90000                         |744.64531                         |75          |NULL                     |NULL                      |NULL                      |11760.40000           |NULL                               |NULL                                |NULL                                |NULL                            |NULL                                  |NULL                                   |NULL                                   |NULL                               |130009.87500         |130621.46666          |130567.36206          |68499.19481       |6718.50000                     |7046.06666                      |6798.70689                      |6911.67808                  |63.250                            |66.666                             |65.551                             |65.849                         |174148.43750              |173495.50000               |173275.93103               |65292.88750            |1669.375                     |1680.666                      |1681.034                      |631.692                   |
|2022-10-12  |PM       |Madrid          |14384          |Chinese       |136             |10               |3              |3.0000        |8831702.00                    |NULL                              |16020.00                                |764333.00                               |3957.16633              |3556.75000                  |514.02564                         |4067.12691                        |142         |14822.00000              |14822.00000               |19284.00000               |23880.55882           |NULL                               |NULL                                |NULL                                |26277.00000                     |NULL                                  |NULL                                   |NULL                                   |166.000                            |427538.37500         |422779.20000          |420569.20689          |166542.07085      |26091.75000                    |25557.00000                     |25333.13793                     |24722.78710                 |188.875                           |182.133                            |181.034                            |174.580                        |583677.00000              |580978.33333               |581725.75862               |228003.59313           |4135.250                     |4096.600                      |4115.206                      |1613.867                  |
|2021-02-23  |AM       |Cape Town       |7470           |Hot Dogs      |101             |2                |2              |8.0000        |2536971.00                    |NULL                              |NULL                                    |NULL                                    |4060.36589              |NULL                        |11512.00000                       |6954.38016                        |1318        |NULL                     |NULL                      |NULL                      |22830.16666           |NULL                               |NULL                                |NULL                                |NULL                            |NULL                                  |NULL                                   |NULL                                   |NULL                               |311803.43750         |311132.26666          |312502.08620          |102960.96838      |43835.25000                    |43016.26666                     |43201.44827                     |42593.03703                 |1552.500                          |1493.866                           |1493.448                           |1475.407                       |211231.50000              |207337.73333               |209194.58620               |53477.35672            |7329.250                     |7184.533                      |7247.000                      |1854.024                  |
|2022-02-15  |PM       |Tokyo           |11864          |Poutine       |116             |2                |2              |3.0000        |3330447.00                    |NULL                              |NULL                                    |NULL                                    |4712.56042              |4521.66666                  |572.25000                         |5628.50000                        |214         |NULL                     |49933.25000               |41338.37500               |31199.39285           |NULL                               |NULL                                |NULL                                |NULL                            |NULL                                  |NULL                                   |NULL                                   |NULL                               |451249.34375         |451510.50000          |450678.46551          |161190.36411      |35811.87500                    |35598.06666                     |35578.00000                     |35626.02857                 |200.250                           |199.333                            |200.241                            |200.142                        |533181.62500              |535600.66666               |535037.37931               |260571.02872           |3039.625                     |3043.266                      |3028.827                      |1472.947                  |
|2022-05-04  |PM       |Cape Town       |7453           |BBQ           |25              |5                |3              |3.0000        |10756766.50                   |NULL                              |NULL                                    |NULL                                    |5225.27426              |6188.14285                  |569.60000                         |3736.19867                        |203         |50810.00000              |50810.00000               |37733.25000               |34060.45370           |NULL                               |NULL                                |NULL                                |NULL                            |NULL                                  |NULL                                   |NULL                                   |NULL                               |629837.28125         |628722.88333          |586445.78448          |221573.70391      |33218.25000                    |33585.73333                     |33840.24137                     |33808.57142                 |185.125                           |188.933                            |192.344                            |190.330                        |725658.37500              |724764.13333               |712518.17241               |264426.58029           |4099.875                     |4103.733                      |4033.827                      |1494.293                  |
|2021-05-22  |PM       |Vancouver       |3899           |Mac & Cheese  |42              |5                |6              |10.0000       |1117714.00                    |NULL                              |60300.00                                |208180.00                               |1436.30000              |979.15384                   |2335.00000                        |1346.61290                        |255         |NULL                     |NULL                      |NULL                      |7601.90000            |NULL                               |NULL                                |NULL                                |NULL                            |NULL                                  |NULL                                   |NULL                                   |NULL                               |100031.68750         |99985.80000           |102374.94827          |34905.97377       |8466.75000                     |8221.06666                      |8416.37931                      |6999.19066                  |247.125                           |240.000                            |245.344                            |201.586                        |292739.62500              |295078.06666               |295732.51724               |173550.96957           |8477.875                     |8500.266                      |8489.862                      |4987.920                  |
|2022-04-13  |PM       |Mumbai          |14070          |Crepes        |84              |4                |3              |2.0000        |7677970.50                    |NULL                              |12134.00                                |1030913.00                              |5754.72983              |4990.46666                  |402.02222                         |5671.39492                        |200         |NULL                     |NULL                      |NULL                      |39035.29166           |NULL                               |NULL                                |NULL                                |33927.00000                     |NULL                                  |NULL                                   |NULL                                   |195.000                            |384595.81250         |381516.90000          |381022.05172          |168666.19742      |33566.87500                    |33790.73333                     |34203.55172                     |34138.96546                 |196.250                           |199.466                            |203.551                            |203.230                        |594394.25000              |597222.66666               |592717.82758               |229685.25610           |3571.000                     |3575.733                      |3535.793                      |1367.530                  |
|2020-07-17  |PM       |Warsaw          |12227          |Chinese       |134             |7                |5              |2.0000        |577524.00                     |NULL                              |8122.00                                 |577524.00                               |3113.92298              |318.00000                   |259.69230                         |3089.82744                        |111         |NULL                     |NULL                      |NULL                      |NULL                  |NULL                               |NULL                                |NULL                                |NULL                            |NULL                                  |NULL                                   |NULL                                   |NULL                               |55277.50000          |52318.40000           |52607.27586           |30691.65454       |14878.37500                    |15075.80000                     |15457.37931                     |18113.38181                 |109.125                           |108.866                            |109.379                            |127.843                        |102341.25000              |98089.93333                |95859.44827                |53581.26363            |727.625                      |699.866                       |685.655                       |379.610                   |
|2021-08-23  |AM       |Mumbai          |13658          |Indian        |142             |8                |1              |18.0000       |5206545.50                    |78696.00                          |421254.00                               |1210086.00                              |5150.42682              |5898.63157                  |13965.04477                       |6695.43398                        |771         |NULL                     |NULL                      |NULL                      |34532.63636           |NULL                               |NULL                                |NULL                                |40177.80000                     |NULL                                  |NULL                                   |NULL                                   |766.000                            |219803.53125         |219819.43333          |219709.93103          |116749.75314      |40201.62500                    |40505.60000                     |40775.27586                     |40173.80377                 |763.375                           |773.066                            |780.689                            |775.326                        |496574.37500              |502887.40000               |507307.37931               |192281.68200           |9581.250                     |9719.600                      |9801.206                      |3712.288                  |
|2022-07-16  |AM       |Paris           |14229          |Gyros         |124             |7                |6              |2.0000        |4292238.00                    |18812.00                          |7244.00                                 |734619.00                               |3445.73458              |459.00000                   |270.11538                         |4443.59633                        |147         |NULL                     |8321.00000                |16331.50000               |18407.66666           |NULL                               |NULL                                |24342.00000                         |24342.00000                     |NULL                                  |NULL                                   |131.000                                |131.000                            |288919.96875         |285921.00000          |290984.10344          |157350.25117      |23173.75000                    |22642.60000                     |23430.10344                     |24622.04109                 |113.125                           |110.333                            |115.758                            |122.926                        |709366.50000              |705975.00000               |703650.20689               |414967.63088           |3586.500                     |3565.733                      |3545.551                      |2082.693                  |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [93]:
merge_df=sales.select( "DATE","LOCATION_ID" , "MENU_TYPE","DAY_OF_WEEK_AVG_CITY_MENU_TYPE","PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE")

In [94]:
mdf=merge_df.to_pandas()

In [95]:
syntax=pd.io.sql.get_schema(mdf, "DEMAND_FORECAST_TRAINING_Base")
session.use_schema("ANALYTICS")
session.sql(

    syntax
).collect()
session.write_pandas(
    df=mdf,
    table_name="DEMAND_FORECAST_TRAINING_Base",
    database="frostbyte_tasty_bytes",
    schema="ANALYTICS",
    quote_identifiers=False,
    overwrite=True)

In [96]:
mdf=session.sql("Select * from ANALYTICS.DEMAND_FORECAST_TRAINING_BASE")

In [120]:
mdf.where(col("PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE").isNull()).count()

1888021

In [124]:
mdf.count()

3403151

In [ ]:
mdfcol(k).isNull()).count()

In [97]:
mdf.show()

-------------------------------------------------------------------------------------------------------------------------
|"DATE"      |"LOCATION_ID"  |"MENU_TYPE"   |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |
-------------------------------------------------------------------------------------------------------------------------
|2021-01-04  |7365           |Ethiopian     |NULL                              |NULL                                    |
|2021-03-29  |9803           |Mac & Cheese  |1971.76056                        |NULL                                    |
|2021-02-19  |9078           |Tacos         |3061.29123                        |799330.5                                |
|2021-11-26  |12513          |Indian        |6702.0201                         |1196902.0                               |
|2021-03-20  |11007          |Crepes        |2897.72693                        |417552.0                                |
|2022-06-20  |3099           |Tacos         |2817.9315                         |NULL                                    |
|2020-11-19  |12204          |Tacos         |1602.97551                        |469471.5                                |
|2021-12-21  |8163           |Indian        |6039.34217                        |990694.0                                |
|2021-12-02  |2439           |Tacos         |143.35256                         |NULL                                    |
|2020-11-02  |15061          |Tacos         |731.24059                         |284096.5                                |
-------------------------------------------------------------------------------------------------------------------------

In [74]:
dropped_df.show()

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"l_08qh_DATE"  |"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"MENU_TYPE"  |"l_jho6_LOCATION_ID"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"LOCATION"          |"CITY"         |"REGION"  |"LAT"              |"LONG"               |"r_c08p_POSTAL_CODE"  |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2021-10-22     |44          |10       |11      |5      |22     |Indian       |3003                  |0                 |8246.0000           |Dragonfly Pavilion  |Seattle        |WA        |47.56624749575556  |-122.36866268608073  |98126                 |52.6                        |52.6                              |0.1                     |0.0                |0.0                 |94                         |
|2021-10-22     |44          |10       |10      |5      |22     |Indian       |3003                  |0                 |8574.0000           |Dragonfly Pavilion  |Seattle        |WA        |47.56624749575556  |-122.36866268608073  |98126                 |52.6                        |52.6                              |0.1                     |0.0                |0.0                 |94                         |
|2021-10-22     |44          |10       |12      |5      |22     |Indian       |3003                  |0                 |17950.0000          |Dragonfly Pavilion  |Seattle        |WA        |47.56624749575556  |-122.36866268608073  |98126                 |52.6                        |52.6                              |0.1                     |0.0                |0.0                 |94                         |
|2021-10-22     |44          |10       |13      |5      |22     |Indian       |3003                  |0                 |8024.0000           |Dragonfly Pavilion  |Seattle        |WA        |47.56624749575556  |-122.36866268608073  |98126                 |52.6                        |52.6                              |0.1                     |0.0                |0.0                 |94                         |
|2021-10-22     |44          |10       |9       |5      |22     |Indian       |3003                  |0                 |12344.0000          |Dragonfly Pavilion  |Seattle        |WA        |47.56624749575556  |-122.36866268608073  |98126                 |52.6                        |52.6                              |0.1                     |0.0                |0.0                 |94                         |
|2021-10-22     |44          |10       |14      |5      |22     |Indian       |3003                  |0                 |5644.0000           |Dragonfly Pavilion  |Seattle        |WA        |47.56624749575556  |-122.36866268608073  |98126                 |52.6                        |52.6                              |0.1                     |0.0                |0.0                 |94                         |
|2021-08-18     |67          |8        |17      |3      |18     |Vegetarian   |2867                  |0                 |11225.0000          |A Caring Hand       |New York City  |NY        |40.7795067390542   |-73.95323502613428   |10128                 |78.3                        |82.9                              |0.0                     |0.0                |0.0                 |97                         |
|2021-08-18     |67          |8        |21      |3      |18     |Vegetarian   |2867                  |0                 |12402.0000          |A Caring Hand       |New York City  |NY        |40.7795067390542   |-73.95323502613428   |10128                 |78.3                        |82.9                              |0.0                     |0.0                |0.0                 |97                         |
|2021-08-18     |67          |8        |20      |3      |18     |Vegetarian   |2867                  |0                 |11967.0000          |A Caring Hand       |New York City  |NY        |40.7795067390542   |-73.95323502613428   |10128                 |78.3                        |82.9                              |0.0                     |0.0                |0.0                 |97                         |
|2021-08-18     |67          |8        |16      |3      |18     |Vegetarian   |2867                  |0                 |14775.0000          |A Caring Hand       |New York City  |NY        |40.7795067390542   |-73.95323502613428   |10128                 |78.3                        |82.9                              |0.0                     |0.0                |0.0                 |97                         |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [98]:
merge_df=dropped_df.join(mdf, (dropped_df['"l_08qh_DATE"'] == mdf["DATE"])& (dropped_df['"MENU_TYPE"'] == mdf["MENU_TYPE"])& (dropped_df['"l_jho6_LOCATION_ID"'] == mdf["Location_ID"]),"inner").drop('"l_08qh_DATE"').drop('"Date"').drop('"l_jho6_LOCATION_ID"')

In [99]:
merge_df.show()

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"l_itt4_MENU_TYPE"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"LOCATION"          |"CITY"   |"REGION"  |"LAT"              |"LONG"               |"r_c08p_POSTAL_CODE"  |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |"DATE"      |"LOCATION_ID"  |"r_khjn_MENU_TYPE"  |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|31          |7        |9       |2      |12     |Ice Cream           |0                 |3432.5000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126                 |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |14      |2      |12     |Ice Cream           |0                 |235.0000            |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126                 |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |10      |2      |12     |Ice Cream           |0                 |1653.5000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126                 |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |11      |2      |12     |Ice Cream           |0                 |2129.5000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126                 |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |8       |2      |12     |Ice Cream           |0                 |2373.0000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126                 |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |12      |2      |12     |Ice Cream           |0                 |3995.0000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126                 |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|31          |7        |13      |2      |12     |Ice Cream           |0                 |3166.0000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126                 |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream           |301.06064                         |112222.0                                |
|44          |10       |16      |5      |8      |Indian              |0                 |8822.0000           |Seacrest Park       |Seattle  |WA        |47.5887688561122   |-122.38090452834078  |98126                 |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |NULL                                    |
|44          |10       |18      |5      |8      |Indian              |0                 |13856.0000          |Seacrest Park       |Seattle  |WA        |47.5887688561122   |-122.38090452834078  |98126                 |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |NULL                                    |
|44          |10       |19      |5      |8      |Indian              |0                 |21328.0000          |Seacrest Park       |Seattle  |WA        |47.5887688561122   |-122.38090452834078  |98126                 |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian              |4929.11111                        |NULL                                    |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [102]:
merge_df = merge_df.withColumnRenamed('"r_khjn_MENU_TYPE"','Menu_Type').withColumnRenamed('"r_c08p_POSTAL_CODE"','POSTAL_CODE')

In [105]:
merge_df=merge_df.drop('"l_itt4_MENU_TYPE"')

In [106]:
merge_df.show()

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"LOCATION"          |"CITY"   |"REGION"  |"LAT"              |"LONG"               |"POSTAL_CODE"  |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |"DATE"      |"LOCATION_ID"  |"MENU_TYPE"  |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|31          |7        |9       |2      |12     |0                 |3432.5000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|31          |7        |14      |2      |12     |0                 |235.0000            |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|31          |7        |10      |2      |12     |0                 |1653.5000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|31          |7        |11      |2      |12     |0                 |2129.5000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|31          |7        |8       |2      |12     |0                 |2373.0000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|31          |7        |12      |2      |12     |0                 |3995.0000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|31          |7        |13      |2      |12     |0                 |3166.0000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|44          |10       |16      |5      |8      |0                 |8822.0000           |Seacrest Park       |Seattle  |WA        |47.5887688561122   |-122.38090452834078  |98126          |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian       |4929.11111                        |NULL                                    |
|44          |10       |18      |5      |8      |0                 |13856.0000          |Seacrest Park       |Seattle  |WA        |47.5887688561122   |-122.38090452834078  |98126          |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian       |4929.11111                        |NULL                                    |
|44          |10       |19      |5      |8      |0                 |21328.0000          |Seacrest Park       |Seattle  |WA        |47.5887688561122   |-122.38090452834078  |98126          |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian       |4929.11111                        |NULL                                    |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

## Null Encoding

In [132]:
nullColumns = []
numRows = merge_df.count()
for k in merge_df.columns:
    
    nullRows = merge_df.where(col(k).isNull()).count()
    columns=[k,nullRows]
    if nullRows>0:
        columns.append(merge_df.stat.approxQuantile(k,[0.5]))
    nullColumns.append(columns)

nullColumns
# ['D']

[['TRUCK_ID', 0],
 ['MONTH', 0],
 ['HOUR', 0],
 ['DOW', 0],
 ['DAY', 0],
 ['PUBLIC_HOLIDAY', 0],
 ['"SUM(ORDER_TOTAL)"', 0],
 ['LOCATION', 0],
 ['CITY', 0],
 ['REGION', 0],
 ['LAT', 0],
 ['LONG', 0],
 ['POSTAL_CODE', 0],
 ['AVG_TEMPERATURE_AIR_2M_F', 0],
 ['AVG_TEMPERATURE_HEATINDEX_2M_F', 0],
 ['TOT_PRECIPITATION_IN', 0],
 ['TOT_SNOWFALL_IN', 0],
 ['TOT_SNOWDEPTH_IN', 0],
 ['AVG_CLOUD_COVER_TOT_PCT', 0],
 ['DATE', 0],
 ['LOCATION_ID', 0],
 ['MENU_TYPE', 0],
 ['DAY_OF_WEEK_AVG_CITY_MENU_TYPE', 186, [1683.1472034615383]],
 ['PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE', 10921, [292095.2258064516]]]

In [135]:
dropped_df=merge_df.na.fill({'DAY_OF_WEEK_AVG_CITY_MENU_TYPE': 1683.1472034615383, 'PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE': 292095.2258064516})

In [138]:
nullColumns = []
numRows = dropped_df.count()
for k in dropped_df.columns:
    
    nullRows = dropped_df.where(col(k).isNull()).count()
    columns=[k,nullRows]
    if nullRows>0:
        columns.append(dropped_df.stat.approxQuantile(k,[0.5]))
    nullColumns.append(columns)

nullColumns
# ['D']

[['TRUCK_ID', 0],
 ['MONTH', 0],
 ['HOUR', 0],
 ['DOW', 0],
 ['DAY', 0],
 ['PUBLIC_HOLIDAY', 0],
 ['"SUM(ORDER_TOTAL)"', 0],
 ['LOCATION', 0],
 ['CITY', 0],
 ['REGION', 0],
 ['LAT', 0],
 ['LONG', 0],
 ['POSTAL_CODE', 0],
 ['AVG_TEMPERATURE_AIR_2M_F', 0],
 ['AVG_TEMPERATURE_HEATINDEX_2M_F', 0],
 ['TOT_PRECIPITATION_IN', 0],
 ['TOT_SNOWFALL_IN', 0],
 ['TOT_SNOWDEPTH_IN', 0],
 ['AVG_CLOUD_COVER_TOT_PCT', 0],
 ['DATE', 0],
 ['LOCATION_ID', 0],
 ['MENU_TYPE', 0],
 ['DAY_OF_WEEK_AVG_CITY_MENU_TYPE', 0],
 ['PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE', 0]]

In [119]:
merge_df.count()

23566


### Encoding

In [139]:


dropped_df.show()

columns = dropped_df.columns

# Iterate over the columns and count the number of unique values
unique_counts = {}
for column in columns:
    unique_counts[column] = dropped_df.select(column).distinct().count()

# Print the unique counts for each column
for column, count in unique_counts.items():
    print(f"Column '{column}': {count}")

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"LOCATION"          |"CITY"   |"REGION"  |"LAT"              |"LONG"               |"POSTAL_CODE"  |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |"DATE"      |"LOCATION_ID"  |"MENU_TYPE"  |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|31          |7        |9       |2      |12     |0                 |3432.5000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|31          |7        |14      |2      |12     |0                 |235.0000            |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|31          |7        |10      |2      |12     |0                 |1653.5000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|31          |7        |11      |2      |12     |0                 |2129.5000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|31          |7        |8       |2      |12     |0                 |2373.0000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|31          |7        |12      |2      |12     |0                 |3995.0000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|31          |7        |13      |2      |12     |0                 |3166.0000           |Dragonfly Pavilion  |Seattle  |WA        |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |Ice Cream    |301.06064                         |112222.0                                |
|44          |10       |16      |5      |8      |0                 |8822.0000           |Seacrest Park       |Seattle  |WA        |47.5887688561122   |-122.38090452834078  |98126          |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian       |4929.11111                        |292095.2258064516                       |
|44          |10       |18      |5      |8      |0                 |13856.0000          |Seacrest Park       |Seattle  |WA        |47.5887688561122   |-122.38090452834078  |98126          |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian       |4929.11111                        |292095.2258064516                       |
|44          |10       |19      |5      |8      |0                 |21328.0000          |Seacrest Park       |Seattle  |WA        |47.5887688561122   |-122.38090452834078  |98126          |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |Indian       |4929.11111                        |292095.2258064516                       |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Column 'TRUCK_ID': 45
Column 'MONTH': 12
Column 'HOUR': 15
Column 'DOW': 7
Column 'DAY': 31
Column 'PUBLIC_HOLIDAY': 2
Column '"SUM(ORDER_TOTAL)"': 3248
Column 'LOCATION': 16
Column 'CITY': 3
Column 'REGION': 3
Column 'LAT': 14
Column 'LONG': 14
Column 'POSTAL_CODE': 4
Column 'AVG_TEMPERATURE_AIR_2M_F': 312
Column 'AVG_TEMPERATURE_HEATINDEX_2M_F': 320
Column 'TOT_PRECIPITATION_IN': 67
Column 'TOT_SNOWFALL_IN': 16
Column 'TOT_SNOWDEPTH_IN': 26
Column 'AVG_CLOUD_COVER_TOT_PCT': 100
Column 'DATE': 338
Column 'LOCATION_ID': 16
Column 'MENU_TYPE': 15
Column 'DAY_OF_WEEK_AVG_CITY_MENU_TYPE': 3426
Column 'PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE': 231

In [140]:
categoricalColumns = ['MENU_TYPE', 'LOCATION', 'CITY', 'REGION']

In [141]:
def one_hot_encode_columns(df, column_names):
    encoded_df = df
    
    for column_name in column_names:
        unique_values = [row[column_name] for row in df.select(column_name).distinct().collect()]
        
        # Create a new column for each unique value and perform one-hot encoding
        for value in unique_values:
            encoded_column_name = f"{column_name}_{value}_encoded"
            encoded_df = encoded_df.withColumn(encoded_column_name, F.when(F.col(column_name) == value, 1).otherwise(0))
    
    
    return encoded_df

In [142]:
encoded_df = one_hot_encode_columns(dropped_df, categoricalColumns)

In [143]:
final_df = encoded_df.drop(*categoricalColumns)

In [144]:
final_df.show()

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"PUBLIC_HOLIDAY"  |"SUM(ORDER_TOTAL)"  |"LAT"              |"LONG"               |"POSTAL_CODE"  |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |"DATE"      |"LOCATION_ID"  |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |"MENU_TYPE_BBQ_ENCODED"  |"MENU_TYPE_Ice Cream_encoded"  |"MENU_TYPE_GYROS_ENCODED"  |"MENU_TYPE_CREPES_ENCODED"  |"MENU_TYPE_SANDWICHES_ENCODED"  |"MENU_TYPE_Hot Dogs_encoded"  |"MENU_TYPE_Mac & Cheese_encoded"  |"MENU_TYPE_Grilled Cheese_encoded"  |"MENU_TYPE_CHINESE_ENCODED"  |"MENU_TYPE_TACOS_ENCODED"  |"MENU_TYPE_ETHIOPIAN_ENCODED"  |"MENU_TYPE_VEGETARIAN_ENCODED"  |"MENU_TYPE_POUTINE_ENCODED"  |"MENU_TYPE_RAMEN_ENCODED"  |"MENU_TYPE_INDIAN_ENCODED"  |"LOCATION_Inspir Carnegie Hill_encoded"  |"LOCATION_Great Kills Park Hillcrest_encoded"  |"LOCATION_Centennial Gardens_encoded"  |"LOCATION_Meril Gardens_encoded"  |"LOCATION_Orchard Street Ravine_encoded"  |"LOCATION_Dragonfly Pavilion_encoded"  |"LOCATION_Lucy's Whey_encoded"  |"LOCATION_York Playground_encoded"  |"LOCATION_The Jewish Museum_encoded"  |"LOCATION_Dribbl Basketball_encoded"  |"LOCATION_Budget Blinds of West Seattle & Centr...  |"LOCATION_Seacrest Park_encoded"  |"LOCATION_Emeritus at West Seattle_encoded"  |"LOCATION_Ball arena formerly Pepsi Center_enco...  |"LOCATION_A Caring Hand_encoded"  |"LOCATION_Speer Blvd Park_encoded"  |"CITY_SEATTLE_ENCODED"  |"CITY_New York City_encoded"  |"CITY_DENVER_ENCODED"  |"REGION_CO_ENCODED"  |"REGION_NY_ENCODED"  |"REGION_WA_ENCODED"  |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|31          |7        |9       |2      |12     |0                 |3432.5000           |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                            |0                          |0                           |0                                        |0                                              |0                                      |0                                 |0                                         |1                                      |0                               |0                                   |0                                     |0                                     |0                                                   |0                                 |0                                            |0                                                   |0                                 |0                                   |1                       |0                             |0                      |0                    |0                    |1                    |
|31          |7        |14      |2      |12     |0                 |235.0000            |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                            |0                          |0                           |0                                        |0                                              |0                                      |0                                 |0                                         |1                                      |0                               |0                                   |0                                     |0                                     |0                                                   |0                                 |0                                            |0                                                   |0                                 |0                                   |1                       |0                             |0                      |0                    |0                    |1                    |
|31          |7        |10      |2      |12     |0                 |1653.5000           |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                            |0                          |0                           |0                                        |0                                              |0                                      |0                                 |0                                         |1                                      |0                               |0                                   |0                                     |0                                     |0                                                   |0                                 |0                                            |0                                                   |0                                 |0                                   |1                       |0                             |0                      |0                    |0                    |1                    |
|31          |7        |11      |2      |12     |0                 |2129.5000           |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                            |0                          |0                           |0                                        |0                                              |0                                      |0                                 |0                                         |1                                      |0                               |0                                   |0                                     |0                                     |0                                                   |0                                 |0                                            |0                                                   |0                                 |0                                   |1                       |0                             |0                      |0                    |0                    |1                    |
|31          |7        |8       |2      |12     |0                 |2373.0000           |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                            |0                          |0                           |0                                        |0                                              |0                                      |0                                 |0                                         |1                                      |0                               |0                                   |0                                     |0                                     |0                                                   |0                                 |0                                            |0                                                   |0                                 |0                                   |1                       |0                             |0                      |0                    |0                    |1                    |
|31          |7        |12      |2      |12     |0                 |3995.0000           |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                            |0                          |0                           |0                                        |0                                              |0                                      |0                                 |0                                         |1                                      |0                               |0                                   |0                                     |0                                     |0                                                   |0                                 |0                                            |0                                                   |0                                 |0                                   |1                       |0                             |0                      |0                    |0                    |1                    |
|31          |7        |13      |2      |12     |0                 |3166.0000           |47.56624749575556  |-122.36866268608073  |98126          |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |2022-07-12  |3003           |301.06064                         |112222.0                                |0                        |1                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                            |0                          |0                           |0                                        |0                                              |0                                      |0                                 |0                                         |1                                      |0                               |0                                   |0                                     |0                                     |0                                                   |0                                 |0                                            |0                                                   |0                                 |0                                   |1                       |0                             |0                      |0                    |0                    |1                    |
|44          |10       |16      |5      |8      |0                 |8822.0000           |47.5887688561122   |-122.38090452834078  |98126          |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |2021-10-08  |15088          |4929.11111                        |292095.2258064516                       |0                        |0                              |0                          |0                           |0                               |0                             |0                                 |0                                   |0                            |0                          |0                              |0                               |0                            |0                          |1                           |0                                        |0                                              |0                                      |0                                 |0                                         |0                                      |0                               |0                                   |0                                     |0                                     |0                                                   |1                                 |0                                            |0                                                   |0                                 |0                                   |1                       |0                             |0                      |0                    |0                    |1                    |

In [152]:
X_final=final_df[['TRUCK_ID',"MONTH",'HOUR','DOW','DAY','LOCATION_ID','LAT','LONG','AVG_TEMPERATURE_AIR_2M_F',"AVG_TEMPERATURE_HEATINDEX_2M_F","TOT_PRECIPITATION_IN","TOT_SNOWFALL_IN","TOT_SNOWDEPTH_IN","AVG_CLOUD_COVER_TOT_PCT","DAY_OF_WEEK_AVG_CITY_MENU_TYPE","PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE" ]]

In [153]:
X_final.show()

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"TRUCK_ID"  |"MONTH"  |"HOUR"  |"DOW"  |"DAY"  |"LOCATION_ID"  |"LAT"              |"LONG"               |"AVG_TEMPERATURE_AIR_2M_F"  |"AVG_TEMPERATURE_HEATINDEX_2M_F"  |"TOT_PRECIPITATION_IN"  |"TOT_SNOWFALL_IN"  |"TOT_SNOWDEPTH_IN"  |"AVG_CLOUD_COVER_TOT_PCT"  |"DAY_OF_WEEK_AVG_CITY_MENU_TYPE"  |"PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE"  |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|31          |7        |9       |2      |12     |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|31          |7        |14      |2      |12     |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|31          |7        |10      |2      |12     |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|31          |7        |11      |2      |12     |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|31          |7        |8       |2      |12     |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|31          |7        |12      |2      |12     |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|31          |7        |13      |2      |12     |3003           |47.56624749575556  |-122.36866268608073  |67.7                        |68.0                              |0.0                     |0.0                |0.0                 |8                          |301.06064                         |112222.0                                |
|44          |10       |16      |5      |8      |15088          |47.5887688561122   |-122.38090452834078  |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |4929.11111                        |292095.2258064516                       |
|44          |10       |18      |5      |8      |15088          |47.5887688561122   |-122.38090452834078  |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |4929.11111                        |292095.2258064516                       |
|44          |10       |19      |5      |8      |15088          |47.5887688561122   |-122.38090452834078  |48.6                        |48.6                              |0.0                     |0.0                |0.0                 |50                         |4929.11111                        |292095.2258064516                       |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [154]:
X_final=X_final.to_pandas()

In [155]:
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, MaxAbsScaler
scaler=StandardScaler()
scaler.fit(X_final)
X_final_scaled = scaler.transform(X_final)

In [156]:
X_final_scaled=pd.DataFrame(X_final_scaled,columns=X_final.columns)

In [157]:
X_final_scaled.head()

,TRUCK_ID,MONTH,HOUR,DOW,DAY,LOCATION_ID,LAT,LONG,AVG_TEMPERATURE_AIR_2M_F,AVG_TEMPERATURE_HEATINDEX_2M_F,TOT_PRECIPITATION_IN,TOT_SNOWFALL_IN,TOT_SNOWDEPTH_IN,AVG_CLOUD_COVER_TOT_PCT,DAY_OF_WEEK_AVG_CITY_MENU_TYPE,PREV_YEAR_MONTH_SALES_CITY_MENU_TYPE
0,-0.71705,0.072176,0.513137,0.452845,0.694936,-0.699511,1.234283,-1.055315,0.556419,0.54236,-0.43925,-0.111192,-0.199874,-0.876193,-0.861753,-0.355884
1,-0.71705,0.072176,0.983035,0.452845,0.694936,-0.699511,1.234283,-1.055315,0.556419,0.54236,-0.43925,-0.111192,-0.199874,-0.876193,-0.861753,-0.355884
2,-0.71705,0.072176,0.748086,0.452845,0.694936,-0.699511,1.234283,-1.055315,0.556419,0.54236,-0.43925,-0.111192,-0.199874,-0.876193,-0.861753,-0.355884
3,-0.71705,0.072176,1.687881,0.452845,0.694936,-0.699511,1.234283,-1.055315,0.556419,0.54236,-0.43925,-0.111192,-0.199874,-0.876193,-0.861753,-0.355884
4,-0.71705,0.072176,0.278188,0.452845,0.694936,-0.699511,1.234283,-1.055315,0.556419,0.54236,-0.43925,-0.111192,-0.199874,-0.876193,-0.861753,-0.355884

In [158]:
session.use_schema("ANALYTICS")
# final_df.write.save_as_table(table_name="Encoded_Data", mode='overwrite')